// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/bnema/dumber/internal/application/port"
	mock "github.com/stretchr/testify/mock"
)

// MockWebViewPool is an autogenerated mock type for the WebViewPool type
type MockWebViewPool struct {
	mock.Mock
}

type MockWebViewPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebViewPool) EXPECT() *MockWebViewPool_Expecter {
	return &MockWebViewPool_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx
func (_m *MockWebViewPool) Acquire(ctx context.Context) (port.WebView, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 port.WebView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (port.WebView, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) port.WebView); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.WebView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebViewPool_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockWebViewPool_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebViewPool_Expecter) Acquire(ctx interface{}) *MockWebViewPool_Acquire_Call {
	return &MockWebViewPool_Acquire_Call{Call: _e.mock.On("Acquire", ctx)}
}

func (_c *MockWebViewPool_Acquire_Call) Run(run func(ctx context.Context)) *MockWebViewPool_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebViewPool_Acquire_Call) Return(_a0 port.WebView, _a1 error) *MockWebViewPool_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebViewPool_Acquire_Call) RunAndReturn(run func(context.Context) (port.WebView, error)) *MockWebViewPool_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockWebViewPool) Close() {
	_m.Called()
}

// MockWebViewPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWebViewPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWebViewPool_Expecter) Close() *MockWebViewPool_Close_Call {
	return &MockWebViewPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWebViewPool_Close_Call) Run(run func()) *MockWebViewPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebViewPool_Close_Call) Return() *MockWebViewPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebViewPool_Close_Call) RunAndReturn(run func()) *MockWebViewPool_Close_Call {
	_c.Run(run)
	return _c
}

// Prewarm provides a mock function with given fields: count
func (_m *MockWebViewPool) Prewarm(count int) {
	_m.Called(count)
}

// MockWebViewPool_Prewarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prewarm'
type MockWebViewPool_Prewarm_Call struct {
	*mock.Call
}

// Prewarm is a helper method to define mock.On call
//   - count int
func (_e *MockWebViewPool_Expecter) Prewarm(count interface{}) *MockWebViewPool_Prewarm_Call {
	return &MockWebViewPool_Prewarm_Call{Call: _e.mock.On("Prewarm", count)}
}

func (_c *MockWebViewPool_Prewarm_Call) Run(run func(count int)) *MockWebViewPool_Prewarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockWebViewPool_Prewarm_Call) Return() *MockWebViewPool_Prewarm_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebViewPool_Prewarm_Call) RunAndReturn(run func(int)) *MockWebViewPool_Prewarm_Call {
	_c.Run(run)
	return _c
}

// Release provides a mock function with given fields: wv
func (_m *MockWebViewPool) Release(wv port.WebView) {
	_m.Called(wv)
}

// MockWebViewPool_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockWebViewPool_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - wv port.WebView
func (_e *MockWebViewPool_Expecter) Release(wv interface{}) *MockWebViewPool_Release_Call {
	return &MockWebViewPool_Release_Call{Call: _e.mock.On("Release", wv)}
}

func (_c *MockWebViewPool_Release_Call) Run(run func(wv port.WebView)) *MockWebViewPool_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(port.WebView))
	})
	return _c
}

func (_c *MockWebViewPool_Release_Call) Return() *MockWebViewPool_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebViewPool_Release_Call) RunAndReturn(run func(port.WebView)) *MockWebViewPool_Release_Call {
	_c.Run(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockWebViewPool) Size() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockWebViewPool_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockWebViewPool_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockWebViewPool_Expecter) Size() *MockWebViewPool_Size_Call {
	return &MockWebViewPool_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockWebViewPool_Size_Call) Run(run func()) *MockWebViewPool_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebViewPool_Size_Call) Return(_a0 int) *MockWebViewPool_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebViewPool_Size_Call) RunAndReturn(run func() int) *MockWebViewPool_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebViewPool creates a new instance of MockWebViewPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebViewPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebViewPool {
	mock := &MockWebViewPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
