// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/dumber/internal/application/port"
	"github.com/bnema/dumber/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPermissionDialogPresenter creates a new instance of MockPermissionDialogPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionDialogPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionDialogPresenter {
	mock := &MockPermissionDialogPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPermissionDialogPresenter is an autogenerated mock type for the PermissionDialogPresenter type
type MockPermissionDialogPresenter struct {
	mock.Mock
}

type MockPermissionDialogPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionDialogPresenter) EXPECT() *MockPermissionDialogPresenter_Expecter {
	return &MockPermissionDialogPresenter_Expecter{mock: &_m.Mock}
}

// ShowPermissionDialog provides a mock function for the type MockPermissionDialogPresenter
func (_mock *MockPermissionDialogPresenter) ShowPermissionDialog(ctx context.Context, origin string, permTypes []entity.PermissionType, metadata entity.PermissionMetadata, callback func(result port.PermissionDialogResult)) {
	_mock.Called(ctx, origin, permTypes, metadata, callback)
	return
}

// MockPermissionDialogPresenter_ShowPermissionDialog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowPermissionDialog'
type MockPermissionDialogPresenter_ShowPermissionDialog_Call struct {
	*mock.Call
}

// ShowPermissionDialog is a helper method to define mock.On call
//   - ctx context.Context
//   - origin string
//   - permTypes []entity.PermissionType
//   - metadata entity.PermissionMetadata
//   - callback func(result port.PermissionDialogResult)
func (_e *MockPermissionDialogPresenter_Expecter) ShowPermissionDialog(ctx any, origin any, permTypes any, metadata any, callback any) *MockPermissionDialogPresenter_ShowPermissionDialog_Call {
	return &MockPermissionDialogPresenter_ShowPermissionDialog_Call{Call: _e.mock.On("ShowPermissionDialog", ctx, origin, permTypes, metadata, callback)}
}

func (_c *MockPermissionDialogPresenter_ShowPermissionDialog_Call) Run(run func(ctx context.Context, origin string, permTypes []entity.PermissionType, metadata entity.PermissionMetadata, callback func(result port.PermissionDialogResult))) *MockPermissionDialogPresenter_ShowPermissionDialog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entity.PermissionType
		if args[2] != nil {
			arg2 = args[2].([]entity.PermissionType)
		}
		var arg3 entity.PermissionMetadata
		if args[3] != nil {
			arg3 = args[3].(entity.PermissionMetadata)
		}
		var arg4 func(result port.PermissionDialogResult)
		if args[4] != nil {
			arg4 = args[4].(func(result port.PermissionDialogResult))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPermissionDialogPresenter_ShowPermissionDialog_Call) Return() *MockPermissionDialogPresenter_ShowPermissionDialog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPermissionDialogPresenter_ShowPermissionDialog_Call) RunAndReturn(run func(ctx context.Context, origin string, permTypes []entity.PermissionType, metadata entity.PermissionMetadata, callback func(result port.PermissionDialogResult))) *MockPermissionDialogPresenter_ShowPermissionDialog_Call {
	_c.Run(run)
	return _c
}
