// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRuntimeVersionProbe creates a new instance of MockRuntimeVersionProbe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeVersionProbe(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeVersionProbe {
	mock := &MockRuntimeVersionProbe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuntimeVersionProbe is an autogenerated mock type for the RuntimeVersionProbe type
type MockRuntimeVersionProbe struct {
	mock.Mock
}

type MockRuntimeVersionProbe_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeVersionProbe) EXPECT() *MockRuntimeVersionProbe_Expecter {
	return &MockRuntimeVersionProbe_Expecter{mock: &_m.Mock}
}

// PkgConfigModVersion provides a mock function for the type MockRuntimeVersionProbe
func (_mock *MockRuntimeVersionProbe) PkgConfigModVersion(ctx context.Context, pkgName string, prefix string) (string, error) {
	ret := _mock.Called(ctx, pkgName, prefix)

	if len(ret) == 0 {
		panic("no return value specified for PkgConfigModVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, pkgName, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, pkgName, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, pkgName, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuntimeVersionProbe_PkgConfigModVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PkgConfigModVersion'
type MockRuntimeVersionProbe_PkgConfigModVersion_Call struct {
	*mock.Call
}

// PkgConfigModVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - pkgName string
//   - prefix string
func (_e *MockRuntimeVersionProbe_Expecter) PkgConfigModVersion(ctx any, pkgName any, prefix any) *MockRuntimeVersionProbe_PkgConfigModVersion_Call {
	return &MockRuntimeVersionProbe_PkgConfigModVersion_Call{Call: _e.mock.On("PkgConfigModVersion", ctx, pkgName, prefix)}
}

func (_c *MockRuntimeVersionProbe_PkgConfigModVersion_Call) Run(run func(ctx context.Context, pkgName string, prefix string)) *MockRuntimeVersionProbe_PkgConfigModVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRuntimeVersionProbe_PkgConfigModVersion_Call) Return(s string, err error) *MockRuntimeVersionProbe_PkgConfigModVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRuntimeVersionProbe_PkgConfigModVersion_Call) RunAndReturn(run func(ctx context.Context, pkgName string, prefix string) (string, error)) *MockRuntimeVersionProbe_PkgConfigModVersion_Call {
	_c.Call.Return(run)
	return _c
}
