// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/dumber/internal/application/port"
	"github.com/bnema/dumber/internal/domain/entity"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionLogger creates a new instance of MockSessionLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionLogger {
	mock := &MockSessionLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionLogger is an autogenerated mock type for the SessionLogger type
type MockSessionLogger struct {
	mock.Mock
}

type MockSessionLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionLogger) EXPECT() *MockSessionLogger_Expecter {
	return &MockSessionLogger_Expecter{mock: &_m.Mock}
}

// CreateLogger provides a mock function for the type MockSessionLogger
func (_mock *MockSessionLogger) CreateLogger(ctx context.Context, sessionID entity.SessionID, cfg port.SessionLogConfig) (zerolog.Logger, func(), error) {
	ret := _mock.Called(ctx, sessionID, cfg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogger")
	}

	var r0 zerolog.Logger
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SessionID, port.SessionLogConfig) (zerolog.Logger, func(), error)); ok {
		return returnFunc(ctx, sessionID, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.SessionID, port.SessionLogConfig) zerolog.Logger); ok {
		r0 = returnFunc(ctx, sessionID, cfg)
	} else {
		r0 = ret.Get(0).(zerolog.Logger)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.SessionID, port.SessionLogConfig) func()); ok {
		r1 = returnFunc(ctx, sessionID, cfg)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entity.SessionID, port.SessionLogConfig) error); ok {
		r2 = returnFunc(ctx, sessionID, cfg)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionLogger_CreateLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogger'
type MockSessionLogger_CreateLogger_Call struct {
	*mock.Call
}

// CreateLogger is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID entity.SessionID
//   - cfg port.SessionLogConfig
func (_e *MockSessionLogger_Expecter) CreateLogger(ctx any, sessionID any, cfg any) *MockSessionLogger_CreateLogger_Call {
	return &MockSessionLogger_CreateLogger_Call{Call: _e.mock.On("CreateLogger", ctx, sessionID, cfg)}
}

func (_c *MockSessionLogger_CreateLogger_Call) Run(run func(ctx context.Context, sessionID entity.SessionID, cfg port.SessionLogConfig)) *MockSessionLogger_CreateLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.SessionID
		if args[1] != nil {
			arg1 = args[1].(entity.SessionID)
		}
		var arg2 port.SessionLogConfig
		if args[2] != nil {
			arg2 = args[2].(port.SessionLogConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionLogger_CreateLogger_Call) Return(logger zerolog.Logger, fn func(), err error) *MockSessionLogger_CreateLogger_Call {
	_c.Call.Return(logger, fn, err)
	return _c
}

func (_c *MockSessionLogger_CreateLogger_Call) RunAndReturn(run func(ctx context.Context, sessionID entity.SessionID, cfg port.SessionLogConfig) (zerolog.Logger, func(), error)) *MockSessionLogger_CreateLogger_Call {
	_c.Call.Return(run)
	return _c
}
