# GoReleaser configuration for dumber browser
# https://goreleaser.com
version: 2

before:
  hooks:
    # Build frontend assets before building binaries
    - make build-frontend

builds:
  # Pure Go build (no CGO required)
  - id: dumber
    main: ./cmd/dumber
    binary: dumber

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64

    # Version information via ldflags (matching your Makefile)
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: "{{ .ProjectName }}_{{ .Version }}"
    format_overrides:
      - goos: linux
        formats: ['tar.gz']
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - dev.bnema.Dumber.desktop
      - src: assets/logo-512.png
        dst: .
        strip_parent: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build\(deps\):'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: 'Features'
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: 'Performance'
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: 'Refactoring'
      regexp: '^refactor(\(.+\))?:'
      order: 3
    - title: 'Documentation'
      regexp: '^docs(\(.+\))?:'
      order: 4
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: bnema
    name: dumber

  # Don't auto-publish as draft initially
  draft: false

  # Replace existing draft if it exists
  replace_existing_draft: true

  # Header for release notes
  header: |
    ## {{.Tag}} Release (amd64 Linux)

    Released on {{.Date}}

  # Footer with installation instructions
  footer: |
    ---

    ## Installation

    ### Linux (x86_64/amd64)
    ```bash
    # Download latest release
    wget https://github.com/bnema/dumber/releases/latest/download/dumber_linux_x86_64.tar.gz

    # Extract and install to ~/.local/bin (enables auto-updates)
    tar -xzf dumber_linux_x86_64.tar.gz
    mkdir -p ~/.local/bin
    install -m 755 dumber_*/dumber ~/.local/bin/

    # Ensure ~/.local/bin is in your PATH (add to ~/.bashrc or ~/.zshrc if needed)
    # export PATH="$HOME/.local/bin:$PATH"
    ```

    ### Dependencies

    **Arch Linux:**
    ```bash
    # Core WebKitGTK 6.0 and GTK4
    sudo pacman -S webkitgtk-6.0 gtk4

    # GStreamer for media playback
    sudo pacman -S gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-plugin-pipewire pipewire pipewire-pulse

    # Hardware acceleration (choose based on your GPU)
    # AMD: sudo pacman -S gstreamer-vaapi mesa
    # NVIDIA: sudo pacman -S gstreamer-vaapi libva-nvidia-driver
    # Intel: sudo pacman -S gstreamer-vaapi libva-intel-driver intel-media-driver
    ```

    **Debian/Ubuntu:**
    ```bash
    # Core WebKitGTK and GTK4
    sudo apt install libwebkitgtk-6.0-4 libgtk-4-1

    # GStreamer for media playback
    sudo apt install gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-pipewire

    # Hardware acceleration
    sudo apt install gstreamer1.0-vaapi va-driver-all
    ```

    ---

    **Full Changelog**: https://github.com/bnema/dumber/compare/{{.PreviousTag}}...{{.Tag}}

  # Auto-detect prerelease from version (v1.0.0-rc1, v1.0.0-alpha, etc.)
  prerelease: auto

  # Mark as latest release
  make_latest: true

  # Replace existing release notes
  mode: replace
