template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/bnema/dumber/internal/application/port:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: mocks.go
      pkgname: mocks
    interfaces:
      ConfigMigrator: {}
      DatabaseProvider: {}
      DiffFormatter: {}
      SessionLogger: {}
      SessionSpawner: {}
      TabListProvider: {}
      WebView: {}
      WebViewFactory: {}
      WebViewPool: {}
  github.com/bnema/dumber/internal/domain/repository:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: mocks.go
      pkgname: mocks
    interfaces:
      ContentWhitelistRepository: {}
      FavoriteRepository: {}
      FolderRepository: {}
      HistoryRepository: {}
      SessionRepository: {}
      SessionStateRepository: {}
      TagRepository: {}
      ZoomRepository: {}
  github.com/bnema/dumber/internal/infrastructure/filtering:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: mocks.go
      pkgname: mocks
    interfaces:
      FilterDownloader: {}
      FilterStore: {}
  github.com/bnema/dumber/internal/ui/layout:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: mocks.go
      pkgname: mocks
    interfaces:
      BoxWidget: {}
      ButtonWidget: {}
      ImageWidget: {}
      LabelWidget: {}
      OverlayWidget: {}
      PaneRenderer: {}
      PaneViewFactory: {}
      PanedWidget: {}
      ProgressBarWidget: {}
      SpinnerWidget: {}
      Widget: {}
      WidgetFactory: {}
