template: testify
template-data:
  unroll-variadic: true
filename: mocks.go
packages:
  github.com/bnema/dumber/internal/application/port:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      structname: Mock{{.InterfaceName}}
      pkgname: mocks
    interfaces:
      WebView: {}
      WebViewFactory: {}
      WebViewPool: {}
  github.com/bnema/dumber/internal/domain/repository:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      structname: Mock{{.InterfaceName}}
      pkgname: mocks
    interfaces:
      ContentWhitelistRepository: {}
      FavoriteRepository: {}
      FolderRepository: {}
      HistoryRepository: {}
      TagRepository: {}
      ZoomRepository: {}
  github.com/bnema/dumber/internal/infrastructure/filtering:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      structname: Mock{{.InterfaceName}}
      pkgname: mocks
    interfaces:
      FilterDownloader: {}
      FilterStore: {}
  github.com/bnema/dumber/internal/ui/layout:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      structname: Mock{{.InterfaceName}}
      pkgname: mocks
    interfaces:
      BoxWidget: {}
      ButtonWidget: {}
      ImageWidget: {}
      LabelWidget: {}
      OverlayWidget: {}
      PaneRenderer: {}
      PaneViewFactory: {}
      PanedWidget: {}
      ProgressBarWidget: {}
      Widget: {}
      WidgetFactory: {}
