packages:
  github.com/bnema/dumber/internal/domain/repository:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      HistoryRepository:
      FavoriteRepository:
      FolderRepository:
      TagRepository:
      ZoomRepository:
      ContentWhitelistRepository:
  github.com/bnema/dumber/internal/application/port:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      WebView:
      WebViewPool:
      WebViewFactory:
  github.com/bnema/dumber/internal/ui/layout:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
    interfaces:
      Widget:
      PanedWidget:
      BoxWidget:
      OverlayWidget:
      LabelWidget:
      ButtonWidget:
      ImageWidget:
      ProgressBarWidget:
      WidgetFactory:
      PaneRenderer:
      PaneViewFactory:
