apisecurity:
  requiretoken: false
  token: ''
appearance:
  default_font_size: 16
  defaultfontsize: 16
  monospace_font: Fira Code
  monospacefont: Fira Code
  sans_font: Fira Sans
  sansfont: Fira Sans
  serif_font: Fira Sans
  seriffont: Fira Sans
codec_preferences:
  av1_hardware_only: false
  av1_max_resolution: 1080p
  block_vp8: true
  block_vp9: false
  custom_user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/120.0.0.0 Safari/537.36
  disable_twitch_codec_control: true
  disable_vp9_hardware: false
  force_av1: false
  preferred_codecs: av1,h264
  queue_buffer_time_sec: 10
  video_buffer_size_mb: 16
codecpreferences:
  av1hardwareonly: false
  av1maxresolution: 1080p
  blockvp8: true
  blockvp9: false
  customuseragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/120.0.0.0 Safari/537.36
  disabletwitchcodeccontrol: true
  disablevp9hardware: false
  forceav1: false
  preferredcodecs: av1,h264
  queuebuffertimesec: 10
  videobuffersizemb: 16
database:
  max_connections: 1
  max_idle_time: 300000000000
  maxconnections: 1
  maxidletime: 300000000000
  path: ''
  query_timeout: 30000000000
  querytimeout: 30000000000
debug:
  enable_css_debug: false
  enable_filtering_debug: false
  enable_focus_debug: false
  enable_focus_metrics: false
  enable_general_debug: false
  enable_pane_close_debug: false
  enable_script_debug: false
  enable_webkit_debug: false
  enable_webview_debug: false
  enable_workspace_debug: false
  enablecssdebug: false
  enablefilteringdebug: false
  enablefocusdebug: false
  enablefocusmetrics: false
  enablegeneraldebug: false
  enablepaneclosedebug: false
  enablescriptdebug: false
  enablewebkitdebug: false
  enablewebviewdebug: false
  enableworkspacedebug: false
  logwebkitcrashes: true
  webkitdebugcategories: Network:preconnectTo,ContentFilters
dmenu:
  date_format: 2006-01-02 15:04
  dateformat: 2006-01-02 15:04
  history_prefix: "\U0001F552"
  historyprefix: "\U0001F552"
  max_history_items: 20
  maxhistoryitems: 20
  shortcut_prefix: "\U0001F50D"
  shortcutprefix: "\U0001F50D"
  show_last_visited: true
  show_visit_count: true
  showlastvisited: true
  showvisitcount: true
  sort_by_visit_count: true
  sortbyvisitcount: true
  url_prefix: "\U0001F310"
  urlprefix: "\U0001F310"
history:
  cleanup_interval_days: 1
  cleanupintervaldays: 1
  max_entries: 10000
  maxentries: 10000
  retention_period_days: 365
  retentionperioddays: 365
logging:
  capture_c_output: false
  capture_stderr: false
  capture_stdout: false
  captureconsole: false
  capturecoutput: false
  capturestderr: false
  capturestdout: false
  compress: true
  debug_file: debug.log
  debugfile: debug.log
  enable_file_log: true
  enablefilelog: true
  filename: ''
  format: text
  level: info
  log_dir: /home/brice/.local/state/dumber/logs
  logdir: /home/brice/.local/state/dumber/logs
  max_age: 7
  max_backups: 3
  max_size: 100
  maxage: 7
  maxbackups: 3
  maxsize: 100
  verbose_webkit: false
  verbosewebkit: false
rendering_mode: gpu
renderingmode: gpu
search_shortcuts:
  g:
    description: Google search
    url: https://www.google.com/search?q=%s
  gh:
    description: GitHub search
    url: https://github.com/search?q=%s
  w:
    description: Wikipedia search
    url: https://en.wikipedia.org/wiki/%s
  yt:
    description: YouTube search
    url: https://www.youtube.com/results?search_query=%s
searchshortcuts:
  g:
    description: Google search
    url: https://www.google.com/search?q=%s
  gh:
    description: GitHub search
    url: https://github.com/search?q=%s
  w:
    description: Wikipedia search
    url: https://en.wikipedia.org/wiki/%s
  yt:
    description: YouTube search
    url: https://www.youtube.com/results?search_query=%s
use_dom_zoom: false
usedomzoom: false
video_acceleration:
  auto_detect_gpu: true
  enable_all_drivers: true
  enable_vaapi: true
  legacy_vaapi: false
  vaapi_driver_name: vdpau
videoacceleration:
  autodetectgpu: true
  enablealldrivers: true
  enablevaapi: true
  legacyvaapi: false
  vaapidrivername: ''
webkit_memory:
  cache_model: web_browser
  conservative_threshold: 0.4
  enable_gc_interval: 120
  enable_memory_monitoring: true
  enable_page_cache: true
  kill_threshold: 0.8
  memory_limit_mb: 0
  poll_interval_seconds: 45
  process_recycle_threshold: 50
  strict_threshold: 0.6
webkitmemory:
  cachemodel: web_browser
  conservativethreshold: 0.4
  enablegcinterval: 120
  enablememorymonitoring: true
  enablepagecache: true
  killthreshold: 0.8
  memorylimitmb: 0
  pollintervalseconds: 45
  processrecyclethreshold: 50
  strictthreshold: 0.6
workspace:
  enable_zellij_controls: true
  pane_mode:
    action_bindings:
      arrowdown: split-down
      arrowleft: split-left
      arrowright: split-right
      arrowup: split-up
      d: split-down
      enter: confirm
      escape: cancel
      l: split-left
      r: split-right
      u: split-up
      x: close-pane
    activation_shortcut: cmdorctrl+p
    timeout_ms: 3000
  popups:
    follow_pane_context: true
    open_in_new_pane: true
    placement: right
  styling:
    border_color: '@theme_selected_bg_color'
    border_radius: 0
    border_width: 2
    transition_duration: 120
  tabs:
    close_tab: cmdorctrl+w
    new_tab: cmdorctrl+t
    next_tab: cmdorctrl+tab
    previous_tab: cmdorctrl+shift+tab
