# Docker Compose configuration for goreleaser builds

services:
  # Goreleaser service for building releases
  goreleaser:
    build:
      context: .
      dockerfile: Dockerfile.release
    volumes:
      - .:/workspace
    environment:
      - GITHUB_TOKEN
    working_dir: /workspace
    command: build --snapshot --clean
    network_mode: host

  # Service for full release (with git tag)
  release:
    build:
      context: .
      dockerfile: Dockerfile.release
    volumes:
      - .:/workspace
    environment:
      - GITHUB_TOKEN
    working_dir: /workspace
    command: release --clean
    network_mode: host

  # Service for validation only
  check:
    build:
      context: .
      dockerfile: Dockerfile.release
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: check
