// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	layout "github.com/bnema/dumber/internal/ui/layout"
	gtk "github.com/jwijenbergh/puregotk/v4/gtk"

	mock "github.com/stretchr/testify/mock"
)

// MockWidget is an autogenerated mock type for the Widget type
type MockWidget struct {
	mock.Mock
}

type MockWidget_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWidget) EXPECT() *MockWidget_Expecter {
	return &MockWidget_Expecter{mock: &_m.Mock}
}

// AddController provides a mock function with given fields: controller
func (_m *MockWidget) AddController(controller *gtk.EventController) {
	_m.Called(controller)
}

// MockWidget_AddController_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddController'
type MockWidget_AddController_Call struct {
	*mock.Call
}

// AddController is a helper method to define mock.On call
//   - controller *gtk.EventController
func (_e *MockWidget_Expecter) AddController(controller interface{}) *MockWidget_AddController_Call {
	return &MockWidget_AddController_Call{Call: _e.mock.On("AddController", controller)}
}

func (_c *MockWidget_AddController_Call) Run(run func(controller *gtk.EventController)) *MockWidget_AddController_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gtk.EventController))
	})
	return _c
}

func (_c *MockWidget_AddController_Call) Return() *MockWidget_AddController_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_AddController_Call) RunAndReturn(run func(*gtk.EventController)) *MockWidget_AddController_Call {
	_c.Run(run)
	return _c
}

// AddCssClass provides a mock function with given fields: cssClass
func (_m *MockWidget) AddCssClass(cssClass string) {
	_m.Called(cssClass)
}

// MockWidget_AddCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCssClass'
type MockWidget_AddCssClass_Call struct {
	*mock.Call
}

// AddCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockWidget_Expecter) AddCssClass(cssClass interface{}) *MockWidget_AddCssClass_Call {
	return &MockWidget_AddCssClass_Call{Call: _e.mock.On("AddCssClass", cssClass)}
}

func (_c *MockWidget_AddCssClass_Call) Run(run func(cssClass string)) *MockWidget_AddCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWidget_AddCssClass_Call) Return() *MockWidget_AddCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_AddCssClass_Call) RunAndReturn(run func(string)) *MockWidget_AddCssClass_Call {
	_c.Run(run)
	return _c
}

// ComputePoint provides a mock function with given fields: target
func (_m *MockWidget) ComputePoint(target layout.Widget) (float64, float64, bool) {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for ComputePoint")
	}

	var r0 float64
	var r1 float64
	var r2 bool
	if rf, ok := ret.Get(0).(func(layout.Widget) (float64, float64, bool)); ok {
		return rf(target)
	}
	if rf, ok := ret.Get(0).(func(layout.Widget) float64); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(layout.Widget) float64); ok {
		r1 = rf(target)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(layout.Widget) bool); ok {
		r2 = rf(target)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockWidget_ComputePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputePoint'
type MockWidget_ComputePoint_Call struct {
	*mock.Call
}

// ComputePoint is a helper method to define mock.On call
//   - target layout.Widget
func (_e *MockWidget_Expecter) ComputePoint(target interface{}) *MockWidget_ComputePoint_Call {
	return &MockWidget_ComputePoint_Call{Call: _e.mock.On("ComputePoint", target)}
}

func (_c *MockWidget_ComputePoint_Call) Run(run func(target layout.Widget)) *MockWidget_ComputePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget))
	})
	return _c
}

func (_c *MockWidget_ComputePoint_Call) Return(x float64, y float64, ok bool) *MockWidget_ComputePoint_Call {
	_c.Call.Return(x, y, ok)
	return _c
}

func (_c *MockWidget_ComputePoint_Call) RunAndReturn(run func(layout.Widget) (float64, float64, bool)) *MockWidget_ComputePoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedHeight provides a mock function with no fields
func (_m *MockWidget) GetAllocatedHeight() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedHeight")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockWidget_GetAllocatedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedHeight'
type MockWidget_GetAllocatedHeight_Call struct {
	*mock.Call
}

// GetAllocatedHeight is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GetAllocatedHeight() *MockWidget_GetAllocatedHeight_Call {
	return &MockWidget_GetAllocatedHeight_Call{Call: _e.mock.On("GetAllocatedHeight")}
}

func (_c *MockWidget_GetAllocatedHeight_Call) Run(run func()) *MockWidget_GetAllocatedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GetAllocatedHeight_Call) Return(_a0 int) *MockWidget_GetAllocatedHeight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GetAllocatedHeight_Call) RunAndReturn(run func() int) *MockWidget_GetAllocatedHeight_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedWidth provides a mock function with no fields
func (_m *MockWidget) GetAllocatedWidth() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedWidth")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockWidget_GetAllocatedWidth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedWidth'
type MockWidget_GetAllocatedWidth_Call struct {
	*mock.Call
}

// GetAllocatedWidth is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GetAllocatedWidth() *MockWidget_GetAllocatedWidth_Call {
	return &MockWidget_GetAllocatedWidth_Call{Call: _e.mock.On("GetAllocatedWidth")}
}

func (_c *MockWidget_GetAllocatedWidth_Call) Run(run func()) *MockWidget_GetAllocatedWidth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GetAllocatedWidth_Call) Return(_a0 int) *MockWidget_GetAllocatedWidth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GetAllocatedWidth_Call) RunAndReturn(run func() int) *MockWidget_GetAllocatedWidth_Call {
	_c.Call.Return(run)
	return _c
}

// GetHexpand provides a mock function with no fields
func (_m *MockWidget) GetHexpand() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHexpand")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_GetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHexpand'
type MockWidget_GetHexpand_Call struct {
	*mock.Call
}

// GetHexpand is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GetHexpand() *MockWidget_GetHexpand_Call {
	return &MockWidget_GetHexpand_Call{Call: _e.mock.On("GetHexpand")}
}

func (_c *MockWidget_GetHexpand_Call) Run(run func()) *MockWidget_GetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GetHexpand_Call) Return(_a0 bool) *MockWidget_GetHexpand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GetHexpand_Call) RunAndReturn(run func() bool) *MockWidget_GetHexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GetParent provides a mock function with no fields
func (_m *MockWidget) GetParent() layout.Widget {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 layout.Widget
	if rf, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}

	return r0
}

// MockWidget_GetParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParent'
type MockWidget_GetParent_Call struct {
	*mock.Call
}

// GetParent is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GetParent() *MockWidget_GetParent_Call {
	return &MockWidget_GetParent_Call{Call: _e.mock.On("GetParent")}
}

func (_c *MockWidget_GetParent_Call) Run(run func()) *MockWidget_GetParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GetParent_Call) Return(_a0 layout.Widget) *MockWidget_GetParent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GetParent_Call) RunAndReturn(run func() layout.Widget) *MockWidget_GetParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetVexpand provides a mock function with no fields
func (_m *MockWidget) GetVexpand() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVexpand")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_GetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVexpand'
type MockWidget_GetVexpand_Call struct {
	*mock.Call
}

// GetVexpand is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GetVexpand() *MockWidget_GetVexpand_Call {
	return &MockWidget_GetVexpand_Call{Call: _e.mock.On("GetVexpand")}
}

func (_c *MockWidget_GetVexpand_Call) Run(run func()) *MockWidget_GetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GetVexpand_Call) Return(_a0 bool) *MockWidget_GetVexpand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GetVexpand_Call) RunAndReturn(run func() bool) *MockWidget_GetVexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GrabFocus provides a mock function with no fields
func (_m *MockWidget) GrabFocus() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GrabFocus")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_GrabFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrabFocus'
type MockWidget_GrabFocus_Call struct {
	*mock.Call
}

// GrabFocus is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GrabFocus() *MockWidget_GrabFocus_Call {
	return &MockWidget_GrabFocus_Call{Call: _e.mock.On("GrabFocus")}
}

func (_c *MockWidget_GrabFocus_Call) Run(run func()) *MockWidget_GrabFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GrabFocus_Call) Return(_a0 bool) *MockWidget_GrabFocus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GrabFocus_Call) RunAndReturn(run func() bool) *MockWidget_GrabFocus_Call {
	_c.Call.Return(run)
	return _c
}

// GtkWidget provides a mock function with no fields
func (_m *MockWidget) GtkWidget() *gtk.Widget {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GtkWidget")
	}

	var r0 *gtk.Widget
	if rf, ok := ret.Get(0).(func() *gtk.Widget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gtk.Widget)
		}
	}

	return r0
}

// MockWidget_GtkWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GtkWidget'
type MockWidget_GtkWidget_Call struct {
	*mock.Call
}

// GtkWidget is a helper method to define mock.On call
func (_e *MockWidget_Expecter) GtkWidget() *MockWidget_GtkWidget_Call {
	return &MockWidget_GtkWidget_Call{Call: _e.mock.On("GtkWidget")}
}

func (_c *MockWidget_GtkWidget_Call) Run(run func()) *MockWidget_GtkWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_GtkWidget_Call) Return(_a0 *gtk.Widget) *MockWidget_GtkWidget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_GtkWidget_Call) RunAndReturn(run func() *gtk.Widget) *MockWidget_GtkWidget_Call {
	_c.Call.Return(run)
	return _c
}

// HasCssClass provides a mock function with given fields: cssClass
func (_m *MockWidget) HasCssClass(cssClass string) bool {
	ret := _m.Called(cssClass)

	if len(ret) == 0 {
		panic("no return value specified for HasCssClass")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(cssClass)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_HasCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCssClass'
type MockWidget_HasCssClass_Call struct {
	*mock.Call
}

// HasCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockWidget_Expecter) HasCssClass(cssClass interface{}) *MockWidget_HasCssClass_Call {
	return &MockWidget_HasCssClass_Call{Call: _e.mock.On("HasCssClass", cssClass)}
}

func (_c *MockWidget_HasCssClass_Call) Run(run func(cssClass string)) *MockWidget_HasCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWidget_HasCssClass_Call) Return(_a0 bool) *MockWidget_HasCssClass_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_HasCssClass_Call) RunAndReturn(run func(string) bool) *MockWidget_HasCssClass_Call {
	_c.Call.Return(run)
	return _c
}

// HasFocus provides a mock function with no fields
func (_m *MockWidget) HasFocus() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasFocus")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_HasFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFocus'
type MockWidget_HasFocus_Call struct {
	*mock.Call
}

// HasFocus is a helper method to define mock.On call
func (_e *MockWidget_Expecter) HasFocus() *MockWidget_HasFocus_Call {
	return &MockWidget_HasFocus_Call{Call: _e.mock.On("HasFocus")}
}

func (_c *MockWidget_HasFocus_Call) Run(run func()) *MockWidget_HasFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_HasFocus_Call) Return(_a0 bool) *MockWidget_HasFocus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_HasFocus_Call) RunAndReturn(run func() bool) *MockWidget_HasFocus_Call {
	_c.Call.Return(run)
	return _c
}

// Hide provides a mock function with no fields
func (_m *MockWidget) Hide() {
	_m.Called()
}

// MockWidget_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type MockWidget_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *MockWidget_Expecter) Hide() *MockWidget_Hide_Call {
	return &MockWidget_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *MockWidget_Hide_Call) Run(run func()) *MockWidget_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_Hide_Call) Return() *MockWidget_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_Hide_Call) RunAndReturn(run func()) *MockWidget_Hide_Call {
	_c.Run(run)
	return _c
}

// IsVisible provides a mock function with no fields
func (_m *MockWidget) IsVisible() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsVisible")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWidget_IsVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVisible'
type MockWidget_IsVisible_Call struct {
	*mock.Call
}

// IsVisible is a helper method to define mock.On call
func (_e *MockWidget_Expecter) IsVisible() *MockWidget_IsVisible_Call {
	return &MockWidget_IsVisible_Call{Call: _e.mock.On("IsVisible")}
}

func (_c *MockWidget_IsVisible_Call) Run(run func()) *MockWidget_IsVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_IsVisible_Call) Return(_a0 bool) *MockWidget_IsVisible_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWidget_IsVisible_Call) RunAndReturn(run func() bool) *MockWidget_IsVisible_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCssClass provides a mock function with given fields: cssClass
func (_m *MockWidget) RemoveCssClass(cssClass string) {
	_m.Called(cssClass)
}

// MockWidget_RemoveCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCssClass'
type MockWidget_RemoveCssClass_Call struct {
	*mock.Call
}

// RemoveCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockWidget_Expecter) RemoveCssClass(cssClass interface{}) *MockWidget_RemoveCssClass_Call {
	return &MockWidget_RemoveCssClass_Call{Call: _e.mock.On("RemoveCssClass", cssClass)}
}

func (_c *MockWidget_RemoveCssClass_Call) Run(run func(cssClass string)) *MockWidget_RemoveCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWidget_RemoveCssClass_Call) Return() *MockWidget_RemoveCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_RemoveCssClass_Call) RunAndReturn(run func(string)) *MockWidget_RemoveCssClass_Call {
	_c.Run(run)
	return _c
}

// SetCanFocus provides a mock function with given fields: canFocus
func (_m *MockWidget) SetCanFocus(canFocus bool) {
	_m.Called(canFocus)
}

// MockWidget_SetCanFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanFocus'
type MockWidget_SetCanFocus_Call struct {
	*mock.Call
}

// SetCanFocus is a helper method to define mock.On call
//   - canFocus bool
func (_e *MockWidget_Expecter) SetCanFocus(canFocus interface{}) *MockWidget_SetCanFocus_Call {
	return &MockWidget_SetCanFocus_Call{Call: _e.mock.On("SetCanFocus", canFocus)}
}

func (_c *MockWidget_SetCanFocus_Call) Run(run func(canFocus bool)) *MockWidget_SetCanFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetCanFocus_Call) Return() *MockWidget_SetCanFocus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetCanFocus_Call) RunAndReturn(run func(bool)) *MockWidget_SetCanFocus_Call {
	_c.Run(run)
	return _c
}

// SetCanTarget provides a mock function with given fields: canTarget
func (_m *MockWidget) SetCanTarget(canTarget bool) {
	_m.Called(canTarget)
}

// MockWidget_SetCanTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanTarget'
type MockWidget_SetCanTarget_Call struct {
	*mock.Call
}

// SetCanTarget is a helper method to define mock.On call
//   - canTarget bool
func (_e *MockWidget_Expecter) SetCanTarget(canTarget interface{}) *MockWidget_SetCanTarget_Call {
	return &MockWidget_SetCanTarget_Call{Call: _e.mock.On("SetCanTarget", canTarget)}
}

func (_c *MockWidget_SetCanTarget_Call) Run(run func(canTarget bool)) *MockWidget_SetCanTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetCanTarget_Call) Return() *MockWidget_SetCanTarget_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetCanTarget_Call) RunAndReturn(run func(bool)) *MockWidget_SetCanTarget_Call {
	_c.Run(run)
	return _c
}

// SetFocusOnClick provides a mock function with given fields: focusOnClick
func (_m *MockWidget) SetFocusOnClick(focusOnClick bool) {
	_m.Called(focusOnClick)
}

// MockWidget_SetFocusOnClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFocusOnClick'
type MockWidget_SetFocusOnClick_Call struct {
	*mock.Call
}

// SetFocusOnClick is a helper method to define mock.On call
//   - focusOnClick bool
func (_e *MockWidget_Expecter) SetFocusOnClick(focusOnClick interface{}) *MockWidget_SetFocusOnClick_Call {
	return &MockWidget_SetFocusOnClick_Call{Call: _e.mock.On("SetFocusOnClick", focusOnClick)}
}

func (_c *MockWidget_SetFocusOnClick_Call) Run(run func(focusOnClick bool)) *MockWidget_SetFocusOnClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetFocusOnClick_Call) Return() *MockWidget_SetFocusOnClick_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetFocusOnClick_Call) RunAndReturn(run func(bool)) *MockWidget_SetFocusOnClick_Call {
	_c.Run(run)
	return _c
}

// SetHalign provides a mock function with given fields: align
func (_m *MockWidget) SetHalign(align gtk.Align) {
	_m.Called(align)
}

// MockWidget_SetHalign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHalign'
type MockWidget_SetHalign_Call struct {
	*mock.Call
}

// SetHalign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockWidget_Expecter) SetHalign(align interface{}) *MockWidget_SetHalign_Call {
	return &MockWidget_SetHalign_Call{Call: _e.mock.On("SetHalign", align)}
}

func (_c *MockWidget_SetHalign_Call) Run(run func(align gtk.Align)) *MockWidget_SetHalign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gtk.Align))
	})
	return _c
}

func (_c *MockWidget_SetHalign_Call) Return() *MockWidget_SetHalign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetHalign_Call) RunAndReturn(run func(gtk.Align)) *MockWidget_SetHalign_Call {
	_c.Run(run)
	return _c
}

// SetHexpand provides a mock function with given fields: expand
func (_m *MockWidget) SetHexpand(expand bool) {
	_m.Called(expand)
}

// MockWidget_SetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHexpand'
type MockWidget_SetHexpand_Call struct {
	*mock.Call
}

// SetHexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockWidget_Expecter) SetHexpand(expand interface{}) *MockWidget_SetHexpand_Call {
	return &MockWidget_SetHexpand_Call{Call: _e.mock.On("SetHexpand", expand)}
}

func (_c *MockWidget_SetHexpand_Call) Run(run func(expand bool)) *MockWidget_SetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetHexpand_Call) Return() *MockWidget_SetHexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetHexpand_Call) RunAndReturn(run func(bool)) *MockWidget_SetHexpand_Call {
	_c.Run(run)
	return _c
}

// SetSizeRequest provides a mock function with given fields: width, height
func (_m *MockWidget) SetSizeRequest(width int, height int) {
	_m.Called(width, height)
}

// MockWidget_SetSizeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSizeRequest'
type MockWidget_SetSizeRequest_Call struct {
	*mock.Call
}

// SetSizeRequest is a helper method to define mock.On call
//   - width int
//   - height int
func (_e *MockWidget_Expecter) SetSizeRequest(width interface{}, height interface{}) *MockWidget_SetSizeRequest_Call {
	return &MockWidget_SetSizeRequest_Call{Call: _e.mock.On("SetSizeRequest", width, height)}
}

func (_c *MockWidget_SetSizeRequest_Call) Run(run func(width int, height int)) *MockWidget_SetSizeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockWidget_SetSizeRequest_Call) Return() *MockWidget_SetSizeRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetSizeRequest_Call) RunAndReturn(run func(int, int)) *MockWidget_SetSizeRequest_Call {
	_c.Run(run)
	return _c
}

// SetValign provides a mock function with given fields: align
func (_m *MockWidget) SetValign(align gtk.Align) {
	_m.Called(align)
}

// MockWidget_SetValign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValign'
type MockWidget_SetValign_Call struct {
	*mock.Call
}

// SetValign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockWidget_Expecter) SetValign(align interface{}) *MockWidget_SetValign_Call {
	return &MockWidget_SetValign_Call{Call: _e.mock.On("SetValign", align)}
}

func (_c *MockWidget_SetValign_Call) Run(run func(align gtk.Align)) *MockWidget_SetValign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gtk.Align))
	})
	return _c
}

func (_c *MockWidget_SetValign_Call) Return() *MockWidget_SetValign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetValign_Call) RunAndReturn(run func(gtk.Align)) *MockWidget_SetValign_Call {
	_c.Run(run)
	return _c
}

// SetVexpand provides a mock function with given fields: expand
func (_m *MockWidget) SetVexpand(expand bool) {
	_m.Called(expand)
}

// MockWidget_SetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVexpand'
type MockWidget_SetVexpand_Call struct {
	*mock.Call
}

// SetVexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockWidget_Expecter) SetVexpand(expand interface{}) *MockWidget_SetVexpand_Call {
	return &MockWidget_SetVexpand_Call{Call: _e.mock.On("SetVexpand", expand)}
}

func (_c *MockWidget_SetVexpand_Call) Run(run func(expand bool)) *MockWidget_SetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetVexpand_Call) Return() *MockWidget_SetVexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetVexpand_Call) RunAndReturn(run func(bool)) *MockWidget_SetVexpand_Call {
	_c.Run(run)
	return _c
}

// SetVisible provides a mock function with given fields: visible
func (_m *MockWidget) SetVisible(visible bool) {
	_m.Called(visible)
}

// MockWidget_SetVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVisible'
type MockWidget_SetVisible_Call struct {
	*mock.Call
}

// SetVisible is a helper method to define mock.On call
//   - visible bool
func (_e *MockWidget_Expecter) SetVisible(visible interface{}) *MockWidget_SetVisible_Call {
	return &MockWidget_SetVisible_Call{Call: _e.mock.On("SetVisible", visible)}
}

func (_c *MockWidget_SetVisible_Call) Run(run func(visible bool)) *MockWidget_SetVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockWidget_SetVisible_Call) Return() *MockWidget_SetVisible_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_SetVisible_Call) RunAndReturn(run func(bool)) *MockWidget_SetVisible_Call {
	_c.Run(run)
	return _c
}

// Show provides a mock function with no fields
func (_m *MockWidget) Show() {
	_m.Called()
}

// MockWidget_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockWidget_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
func (_e *MockWidget_Expecter) Show() *MockWidget_Show_Call {
	return &MockWidget_Show_Call{Call: _e.mock.On("Show")}
}

func (_c *MockWidget_Show_Call) Run(run func()) *MockWidget_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_Show_Call) Return() *MockWidget_Show_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_Show_Call) RunAndReturn(run func()) *MockWidget_Show_Call {
	_c.Run(run)
	return _c
}

// Unparent provides a mock function with no fields
func (_m *MockWidget) Unparent() {
	_m.Called()
}

// MockWidget_Unparent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unparent'
type MockWidget_Unparent_Call struct {
	*mock.Call
}

// Unparent is a helper method to define mock.On call
func (_e *MockWidget_Expecter) Unparent() *MockWidget_Unparent_Call {
	return &MockWidget_Unparent_Call{Call: _e.mock.On("Unparent")}
}

func (_c *MockWidget_Unparent_Call) Run(run func()) *MockWidget_Unparent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidget_Unparent_Call) Return() *MockWidget_Unparent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWidget_Unparent_Call) RunAndReturn(run func()) *MockWidget_Unparent_Call {
	_c.Run(run)
	return _c
}

// NewMockWidget creates a new instance of MockWidget. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWidget(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWidget {
	mock := &MockWidget{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
