// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/dumber/internal/ui/layout"
	"github.com/jwijenbergh/puregotk/v4/gtk"
	mock "github.com/stretchr/testify/mock"
)

// NewMockButtonWidget creates a new instance of MockButtonWidget. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockButtonWidget(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockButtonWidget {
	mock := &MockButtonWidget{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockButtonWidget is an autogenerated mock type for the ButtonWidget type
type MockButtonWidget struct {
	mock.Mock
}

type MockButtonWidget_Expecter struct {
	mock *mock.Mock
}

func (_m *MockButtonWidget) EXPECT() *MockButtonWidget_Expecter {
	return &MockButtonWidget_Expecter{mock: &_m.Mock}
}

// AddCssClass provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) AddCssClass(cssClass string) {
	_mock.Called(cssClass)
	return
}

// MockButtonWidget_AddCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCssClass'
type MockButtonWidget_AddCssClass_Call struct {
	*mock.Call
}

// AddCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockButtonWidget_Expecter) AddCssClass(cssClass interface{}) *MockButtonWidget_AddCssClass_Call {
	return &MockButtonWidget_AddCssClass_Call{Call: _e.mock.On("AddCssClass", cssClass)}
}

func (_c *MockButtonWidget_AddCssClass_Call) Run(run func(cssClass string)) *MockButtonWidget_AddCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_AddCssClass_Call) Return() *MockButtonWidget_AddCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_AddCssClass_Call) RunAndReturn(run func(cssClass string)) *MockButtonWidget_AddCssClass_Call {
	_c.Run(run)
	return _c
}

// ConnectClicked provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) ConnectClicked(callback func()) uint32 {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for ConnectClicked")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func(func()) uint32); ok {
		r0 = returnFunc(callback)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockButtonWidget_ConnectClicked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectClicked'
type MockButtonWidget_ConnectClicked_Call struct {
	*mock.Call
}

// ConnectClicked is a helper method to define mock.On call
//   - callback func()
func (_e *MockButtonWidget_Expecter) ConnectClicked(callback interface{}) *MockButtonWidget_ConnectClicked_Call {
	return &MockButtonWidget_ConnectClicked_Call{Call: _e.mock.On("ConnectClicked", callback)}
}

func (_c *MockButtonWidget_ConnectClicked_Call) Run(run func(callback func())) *MockButtonWidget_ConnectClicked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_ConnectClicked_Call) Return(v uint32) *MockButtonWidget_ConnectClicked_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockButtonWidget_ConnectClicked_Call) RunAndReturn(run func(callback func()) uint32) *MockButtonWidget_ConnectClicked_Call {
	_c.Call.Return(run)
	return _c
}

// GetChild provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GetChild() layout.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChild")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockButtonWidget_GetChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChild'
type MockButtonWidget_GetChild_Call struct {
	*mock.Call
}

// GetChild is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GetChild() *MockButtonWidget_GetChild_Call {
	return &MockButtonWidget_GetChild_Call{Call: _e.mock.On("GetChild")}
}

func (_c *MockButtonWidget_GetChild_Call) Run(run func()) *MockButtonWidget_GetChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GetChild_Call) Return(widget layout.Widget) *MockButtonWidget_GetChild_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockButtonWidget_GetChild_Call) RunAndReturn(run func() layout.Widget) *MockButtonWidget_GetChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetHexpand provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GetHexpand() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHexpand")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_GetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHexpand'
type MockButtonWidget_GetHexpand_Call struct {
	*mock.Call
}

// GetHexpand is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GetHexpand() *MockButtonWidget_GetHexpand_Call {
	return &MockButtonWidget_GetHexpand_Call{Call: _e.mock.On("GetHexpand")}
}

func (_c *MockButtonWidget_GetHexpand_Call) Run(run func()) *MockButtonWidget_GetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GetHexpand_Call) Return(b bool) *MockButtonWidget_GetHexpand_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_GetHexpand_Call) RunAndReturn(run func() bool) *MockButtonWidget_GetHexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GetLabel provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GetLabel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLabel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockButtonWidget_GetLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLabel'
type MockButtonWidget_GetLabel_Call struct {
	*mock.Call
}

// GetLabel is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GetLabel() *MockButtonWidget_GetLabel_Call {
	return &MockButtonWidget_GetLabel_Call{Call: _e.mock.On("GetLabel")}
}

func (_c *MockButtonWidget_GetLabel_Call) Run(run func()) *MockButtonWidget_GetLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GetLabel_Call) Return(s string) *MockButtonWidget_GetLabel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockButtonWidget_GetLabel_Call) RunAndReturn(run func() string) *MockButtonWidget_GetLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetParent provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GetParent() layout.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockButtonWidget_GetParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParent'
type MockButtonWidget_GetParent_Call struct {
	*mock.Call
}

// GetParent is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GetParent() *MockButtonWidget_GetParent_Call {
	return &MockButtonWidget_GetParent_Call{Call: _e.mock.On("GetParent")}
}

func (_c *MockButtonWidget_GetParent_Call) Run(run func()) *MockButtonWidget_GetParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GetParent_Call) Return(widget layout.Widget) *MockButtonWidget_GetParent_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockButtonWidget_GetParent_Call) RunAndReturn(run func() layout.Widget) *MockButtonWidget_GetParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetVexpand provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GetVexpand() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVexpand")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_GetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVexpand'
type MockButtonWidget_GetVexpand_Call struct {
	*mock.Call
}

// GetVexpand is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GetVexpand() *MockButtonWidget_GetVexpand_Call {
	return &MockButtonWidget_GetVexpand_Call{Call: _e.mock.On("GetVexpand")}
}

func (_c *MockButtonWidget_GetVexpand_Call) Run(run func()) *MockButtonWidget_GetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GetVexpand_Call) Return(b bool) *MockButtonWidget_GetVexpand_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_GetVexpand_Call) RunAndReturn(run func() bool) *MockButtonWidget_GetVexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GrabFocus provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GrabFocus() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GrabFocus")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_GrabFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrabFocus'
type MockButtonWidget_GrabFocus_Call struct {
	*mock.Call
}

// GrabFocus is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GrabFocus() *MockButtonWidget_GrabFocus_Call {
	return &MockButtonWidget_GrabFocus_Call{Call: _e.mock.On("GrabFocus")}
}

func (_c *MockButtonWidget_GrabFocus_Call) Run(run func()) *MockButtonWidget_GrabFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GrabFocus_Call) Return(b bool) *MockButtonWidget_GrabFocus_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_GrabFocus_Call) RunAndReturn(run func() bool) *MockButtonWidget_GrabFocus_Call {
	_c.Call.Return(run)
	return _c
}

// GtkWidget provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) GtkWidget() *gtk.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GtkWidget")
	}

	var r0 *gtk.Widget
	if returnFunc, ok := ret.Get(0).(func() *gtk.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gtk.Widget)
		}
	}
	return r0
}

// MockButtonWidget_GtkWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GtkWidget'
type MockButtonWidget_GtkWidget_Call struct {
	*mock.Call
}

// GtkWidget is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) GtkWidget() *MockButtonWidget_GtkWidget_Call {
	return &MockButtonWidget_GtkWidget_Call{Call: _e.mock.On("GtkWidget")}
}

func (_c *MockButtonWidget_GtkWidget_Call) Run(run func()) *MockButtonWidget_GtkWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_GtkWidget_Call) Return(widget *gtk.Widget) *MockButtonWidget_GtkWidget_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockButtonWidget_GtkWidget_Call) RunAndReturn(run func() *gtk.Widget) *MockButtonWidget_GtkWidget_Call {
	_c.Call.Return(run)
	return _c
}

// HasCssClass provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) HasCssClass(cssClass string) bool {
	ret := _mock.Called(cssClass)

	if len(ret) == 0 {
		panic("no return value specified for HasCssClass")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(cssClass)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_HasCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCssClass'
type MockButtonWidget_HasCssClass_Call struct {
	*mock.Call
}

// HasCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockButtonWidget_Expecter) HasCssClass(cssClass interface{}) *MockButtonWidget_HasCssClass_Call {
	return &MockButtonWidget_HasCssClass_Call{Call: _e.mock.On("HasCssClass", cssClass)}
}

func (_c *MockButtonWidget_HasCssClass_Call) Run(run func(cssClass string)) *MockButtonWidget_HasCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_HasCssClass_Call) Return(b bool) *MockButtonWidget_HasCssClass_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_HasCssClass_Call) RunAndReturn(run func(cssClass string) bool) *MockButtonWidget_HasCssClass_Call {
	_c.Call.Return(run)
	return _c
}

// HasFocus provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) HasFocus() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasFocus")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_HasFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFocus'
type MockButtonWidget_HasFocus_Call struct {
	*mock.Call
}

// HasFocus is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) HasFocus() *MockButtonWidget_HasFocus_Call {
	return &MockButtonWidget_HasFocus_Call{Call: _e.mock.On("HasFocus")}
}

func (_c *MockButtonWidget_HasFocus_Call) Run(run func()) *MockButtonWidget_HasFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_HasFocus_Call) Return(b bool) *MockButtonWidget_HasFocus_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_HasFocus_Call) RunAndReturn(run func() bool) *MockButtonWidget_HasFocus_Call {
	_c.Call.Return(run)
	return _c
}

// Hide provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) Hide() {
	_mock.Called()
	return
}

// MockButtonWidget_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type MockButtonWidget_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) Hide() *MockButtonWidget_Hide_Call {
	return &MockButtonWidget_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *MockButtonWidget_Hide_Call) Run(run func()) *MockButtonWidget_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_Hide_Call) Return() *MockButtonWidget_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_Hide_Call) RunAndReturn(run func()) *MockButtonWidget_Hide_Call {
	_c.Run(run)
	return _c
}

// IsVisible provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) IsVisible() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsVisible")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockButtonWidget_IsVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVisible'
type MockButtonWidget_IsVisible_Call struct {
	*mock.Call
}

// IsVisible is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) IsVisible() *MockButtonWidget_IsVisible_Call {
	return &MockButtonWidget_IsVisible_Call{Call: _e.mock.On("IsVisible")}
}

func (_c *MockButtonWidget_IsVisible_Call) Run(run func()) *MockButtonWidget_IsVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_IsVisible_Call) Return(b bool) *MockButtonWidget_IsVisible_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockButtonWidget_IsVisible_Call) RunAndReturn(run func() bool) *MockButtonWidget_IsVisible_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCssClass provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) RemoveCssClass(cssClass string) {
	_mock.Called(cssClass)
	return
}

// MockButtonWidget_RemoveCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCssClass'
type MockButtonWidget_RemoveCssClass_Call struct {
	*mock.Call
}

// RemoveCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockButtonWidget_Expecter) RemoveCssClass(cssClass interface{}) *MockButtonWidget_RemoveCssClass_Call {
	return &MockButtonWidget_RemoveCssClass_Call{Call: _e.mock.On("RemoveCssClass", cssClass)}
}

func (_c *MockButtonWidget_RemoveCssClass_Call) Run(run func(cssClass string)) *MockButtonWidget_RemoveCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_RemoveCssClass_Call) Return() *MockButtonWidget_RemoveCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_RemoveCssClass_Call) RunAndReturn(run func(cssClass string)) *MockButtonWidget_RemoveCssClass_Call {
	_c.Run(run)
	return _c
}

// SetCanFocus provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetCanFocus(canFocus bool) {
	_mock.Called(canFocus)
	return
}

// MockButtonWidget_SetCanFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanFocus'
type MockButtonWidget_SetCanFocus_Call struct {
	*mock.Call
}

// SetCanFocus is a helper method to define mock.On call
//   - canFocus bool
func (_e *MockButtonWidget_Expecter) SetCanFocus(canFocus interface{}) *MockButtonWidget_SetCanFocus_Call {
	return &MockButtonWidget_SetCanFocus_Call{Call: _e.mock.On("SetCanFocus", canFocus)}
}

func (_c *MockButtonWidget_SetCanFocus_Call) Run(run func(canFocus bool)) *MockButtonWidget_SetCanFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetCanFocus_Call) Return() *MockButtonWidget_SetCanFocus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetCanFocus_Call) RunAndReturn(run func(canFocus bool)) *MockButtonWidget_SetCanFocus_Call {
	_c.Run(run)
	return _c
}

// SetChild provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetChild(child layout.Widget) {
	_mock.Called(child)
	return
}

// MockButtonWidget_SetChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChild'
type MockButtonWidget_SetChild_Call struct {
	*mock.Call
}

// SetChild is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockButtonWidget_Expecter) SetChild(child interface{}) *MockButtonWidget_SetChild_Call {
	return &MockButtonWidget_SetChild_Call{Call: _e.mock.On("SetChild", child)}
}

func (_c *MockButtonWidget_SetChild_Call) Run(run func(child layout.Widget)) *MockButtonWidget_SetChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Widget
		if args[0] != nil {
			arg0 = args[0].(layout.Widget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetChild_Call) Return() *MockButtonWidget_SetChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetChild_Call) RunAndReturn(run func(child layout.Widget)) *MockButtonWidget_SetChild_Call {
	_c.Run(run)
	return _c
}

// SetFocusOnClick provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetFocusOnClick(focusOnClick bool) {
	_mock.Called(focusOnClick)
	return
}

// MockButtonWidget_SetFocusOnClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFocusOnClick'
type MockButtonWidget_SetFocusOnClick_Call struct {
	*mock.Call
}

// SetFocusOnClick is a helper method to define mock.On call
//   - focusOnClick bool
func (_e *MockButtonWidget_Expecter) SetFocusOnClick(focusOnClick interface{}) *MockButtonWidget_SetFocusOnClick_Call {
	return &MockButtonWidget_SetFocusOnClick_Call{Call: _e.mock.On("SetFocusOnClick", focusOnClick)}
}

func (_c *MockButtonWidget_SetFocusOnClick_Call) Run(run func(focusOnClick bool)) *MockButtonWidget_SetFocusOnClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetFocusOnClick_Call) Return() *MockButtonWidget_SetFocusOnClick_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetFocusOnClick_Call) RunAndReturn(run func(focusOnClick bool)) *MockButtonWidget_SetFocusOnClick_Call {
	_c.Run(run)
	return _c
}

// SetHalign provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetHalign(align gtk.Align) {
	_mock.Called(align)
	return
}

// MockButtonWidget_SetHalign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHalign'
type MockButtonWidget_SetHalign_Call struct {
	*mock.Call
}

// SetHalign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockButtonWidget_Expecter) SetHalign(align interface{}) *MockButtonWidget_SetHalign_Call {
	return &MockButtonWidget_SetHalign_Call{Call: _e.mock.On("SetHalign", align)}
}

func (_c *MockButtonWidget_SetHalign_Call) Run(run func(align gtk.Align)) *MockButtonWidget_SetHalign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gtk.Align
		if args[0] != nil {
			arg0 = args[0].(gtk.Align)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetHalign_Call) Return() *MockButtonWidget_SetHalign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetHalign_Call) RunAndReturn(run func(align gtk.Align)) *MockButtonWidget_SetHalign_Call {
	_c.Run(run)
	return _c
}

// SetHexpand provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetHexpand(expand bool) {
	_mock.Called(expand)
	return
}

// MockButtonWidget_SetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHexpand'
type MockButtonWidget_SetHexpand_Call struct {
	*mock.Call
}

// SetHexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockButtonWidget_Expecter) SetHexpand(expand interface{}) *MockButtonWidget_SetHexpand_Call {
	return &MockButtonWidget_SetHexpand_Call{Call: _e.mock.On("SetHexpand", expand)}
}

func (_c *MockButtonWidget_SetHexpand_Call) Run(run func(expand bool)) *MockButtonWidget_SetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetHexpand_Call) Return() *MockButtonWidget_SetHexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetHexpand_Call) RunAndReturn(run func(expand bool)) *MockButtonWidget_SetHexpand_Call {
	_c.Run(run)
	return _c
}

// SetLabel provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetLabel(label string) {
	_mock.Called(label)
	return
}

// MockButtonWidget_SetLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabel'
type MockButtonWidget_SetLabel_Call struct {
	*mock.Call
}

// SetLabel is a helper method to define mock.On call
//   - label string
func (_e *MockButtonWidget_Expecter) SetLabel(label interface{}) *MockButtonWidget_SetLabel_Call {
	return &MockButtonWidget_SetLabel_Call{Call: _e.mock.On("SetLabel", label)}
}

func (_c *MockButtonWidget_SetLabel_Call) Run(run func(label string)) *MockButtonWidget_SetLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetLabel_Call) Return() *MockButtonWidget_SetLabel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetLabel_Call) RunAndReturn(run func(label string)) *MockButtonWidget_SetLabel_Call {
	_c.Run(run)
	return _c
}

// SetSizeRequest provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetSizeRequest(width int, height int) {
	_mock.Called(width, height)
	return
}

// MockButtonWidget_SetSizeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSizeRequest'
type MockButtonWidget_SetSizeRequest_Call struct {
	*mock.Call
}

// SetSizeRequest is a helper method to define mock.On call
//   - width int
//   - height int
func (_e *MockButtonWidget_Expecter) SetSizeRequest(width interface{}, height interface{}) *MockButtonWidget_SetSizeRequest_Call {
	return &MockButtonWidget_SetSizeRequest_Call{Call: _e.mock.On("SetSizeRequest", width, height)}
}

func (_c *MockButtonWidget_SetSizeRequest_Call) Run(run func(width int, height int)) *MockButtonWidget_SetSizeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetSizeRequest_Call) Return() *MockButtonWidget_SetSizeRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetSizeRequest_Call) RunAndReturn(run func(width int, height int)) *MockButtonWidget_SetSizeRequest_Call {
	_c.Run(run)
	return _c
}

// SetValign provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetValign(align gtk.Align) {
	_mock.Called(align)
	return
}

// MockButtonWidget_SetValign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValign'
type MockButtonWidget_SetValign_Call struct {
	*mock.Call
}

// SetValign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockButtonWidget_Expecter) SetValign(align interface{}) *MockButtonWidget_SetValign_Call {
	return &MockButtonWidget_SetValign_Call{Call: _e.mock.On("SetValign", align)}
}

func (_c *MockButtonWidget_SetValign_Call) Run(run func(align gtk.Align)) *MockButtonWidget_SetValign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gtk.Align
		if args[0] != nil {
			arg0 = args[0].(gtk.Align)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetValign_Call) Return() *MockButtonWidget_SetValign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetValign_Call) RunAndReturn(run func(align gtk.Align)) *MockButtonWidget_SetValign_Call {
	_c.Run(run)
	return _c
}

// SetVexpand provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetVexpand(expand bool) {
	_mock.Called(expand)
	return
}

// MockButtonWidget_SetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVexpand'
type MockButtonWidget_SetVexpand_Call struct {
	*mock.Call
}

// SetVexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockButtonWidget_Expecter) SetVexpand(expand interface{}) *MockButtonWidget_SetVexpand_Call {
	return &MockButtonWidget_SetVexpand_Call{Call: _e.mock.On("SetVexpand", expand)}
}

func (_c *MockButtonWidget_SetVexpand_Call) Run(run func(expand bool)) *MockButtonWidget_SetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetVexpand_Call) Return() *MockButtonWidget_SetVexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetVexpand_Call) RunAndReturn(run func(expand bool)) *MockButtonWidget_SetVexpand_Call {
	_c.Run(run)
	return _c
}

// SetVisible provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) SetVisible(visible bool) {
	_mock.Called(visible)
	return
}

// MockButtonWidget_SetVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVisible'
type MockButtonWidget_SetVisible_Call struct {
	*mock.Call
}

// SetVisible is a helper method to define mock.On call
//   - visible bool
func (_e *MockButtonWidget_Expecter) SetVisible(visible interface{}) *MockButtonWidget_SetVisible_Call {
	return &MockButtonWidget_SetVisible_Call{Call: _e.mock.On("SetVisible", visible)}
}

func (_c *MockButtonWidget_SetVisible_Call) Run(run func(visible bool)) *MockButtonWidget_SetVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockButtonWidget_SetVisible_Call) Return() *MockButtonWidget_SetVisible_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_SetVisible_Call) RunAndReturn(run func(visible bool)) *MockButtonWidget_SetVisible_Call {
	_c.Run(run)
	return _c
}

// Show provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) Show() {
	_mock.Called()
	return
}

// MockButtonWidget_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockButtonWidget_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) Show() *MockButtonWidget_Show_Call {
	return &MockButtonWidget_Show_Call{Call: _e.mock.On("Show")}
}

func (_c *MockButtonWidget_Show_Call) Run(run func()) *MockButtonWidget_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_Show_Call) Return() *MockButtonWidget_Show_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_Show_Call) RunAndReturn(run func()) *MockButtonWidget_Show_Call {
	_c.Run(run)
	return _c
}

// Unparent provides a mock function for the type MockButtonWidget
func (_mock *MockButtonWidget) Unparent() {
	_mock.Called()
	return
}

// MockButtonWidget_Unparent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unparent'
type MockButtonWidget_Unparent_Call struct {
	*mock.Call
}

// Unparent is a helper method to define mock.On call
func (_e *MockButtonWidget_Expecter) Unparent() *MockButtonWidget_Unparent_Call {
	return &MockButtonWidget_Unparent_Call{Call: _e.mock.On("Unparent")}
}

func (_c *MockButtonWidget_Unparent_Call) Run(run func()) *MockButtonWidget_Unparent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockButtonWidget_Unparent_Call) Return() *MockButtonWidget_Unparent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockButtonWidget_Unparent_Call) RunAndReturn(run func()) *MockButtonWidget_Unparent_Call {
	_c.Run(run)
	return _c
}
