// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/dumber/internal/ui/layout"
	"github.com/jwijenbergh/puregotk/v4/gtk"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPanedWidget creates a new instance of MockPanedWidget. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPanedWidget(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPanedWidget {
	mock := &MockPanedWidget{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPanedWidget is an autogenerated mock type for the PanedWidget type
type MockPanedWidget struct {
	mock.Mock
}

type MockPanedWidget_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPanedWidget) EXPECT() *MockPanedWidget_Expecter {
	return &MockPanedWidget_Expecter{mock: &_m.Mock}
}

// AddController provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) AddController(controller *gtk.EventController) {
	_mock.Called(controller)
	return
}

// MockPanedWidget_AddController_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddController'
type MockPanedWidget_AddController_Call struct {
	*mock.Call
}

// AddController is a helper method to define mock.On call
//   - controller *gtk.EventController
func (_e *MockPanedWidget_Expecter) AddController(controller interface{}) *MockPanedWidget_AddController_Call {
	return &MockPanedWidget_AddController_Call{Call: _e.mock.On("AddController", controller)}
}

func (_c *MockPanedWidget_AddController_Call) Run(run func(controller *gtk.EventController)) *MockPanedWidget_AddController_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gtk.EventController
		if args[0] != nil {
			arg0 = args[0].(*gtk.EventController)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_AddController_Call) Return() *MockPanedWidget_AddController_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_AddController_Call) RunAndReturn(run func(controller *gtk.EventController)) *MockPanedWidget_AddController_Call {
	_c.Run(run)
	return _c
}

// AddCssClass provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) AddCssClass(cssClass string) {
	_mock.Called(cssClass)
	return
}

// MockPanedWidget_AddCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCssClass'
type MockPanedWidget_AddCssClass_Call struct {
	*mock.Call
}

// AddCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockPanedWidget_Expecter) AddCssClass(cssClass interface{}) *MockPanedWidget_AddCssClass_Call {
	return &MockPanedWidget_AddCssClass_Call{Call: _e.mock.On("AddCssClass", cssClass)}
}

func (_c *MockPanedWidget_AddCssClass_Call) Run(run func(cssClass string)) *MockPanedWidget_AddCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_AddCssClass_Call) Return() *MockPanedWidget_AddCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_AddCssClass_Call) RunAndReturn(run func(cssClass string)) *MockPanedWidget_AddCssClass_Call {
	_c.Run(run)
	return _c
}

// AddTickCallback provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) AddTickCallback(callback func() bool) uint {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for AddTickCallback")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func(func() bool) uint); ok {
		r0 = returnFunc(callback)
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// MockPanedWidget_AddTickCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTickCallback'
type MockPanedWidget_AddTickCallback_Call struct {
	*mock.Call
}

// AddTickCallback is a helper method to define mock.On call
//   - callback func() bool
func (_e *MockPanedWidget_Expecter) AddTickCallback(callback interface{}) *MockPanedWidget_AddTickCallback_Call {
	return &MockPanedWidget_AddTickCallback_Call{Call: _e.mock.On("AddTickCallback", callback)}
}

func (_c *MockPanedWidget_AddTickCallback_Call) Run(run func(callback func() bool)) *MockPanedWidget_AddTickCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() bool
		if args[0] != nil {
			arg0 = args[0].(func() bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_AddTickCallback_Call) Return(v uint) *MockPanedWidget_AddTickCallback_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPanedWidget_AddTickCallback_Call) RunAndReturn(run func(callback func() bool) uint) *MockPanedWidget_AddTickCallback_Call {
	_c.Call.Return(run)
	return _c
}

// ComputePoint provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) ComputePoint(target layout.Widget) (float64, float64, bool) {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for ComputePoint")
	}

	var r0 float64
	var r1 float64
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(layout.Widget) (float64, float64, bool)); ok {
		return returnFunc(target)
	}
	if returnFunc, ok := ret.Get(0).(func(layout.Widget) float64); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(layout.Widget) float64); ok {
		r1 = returnFunc(target)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(layout.Widget) bool); ok {
		r2 = returnFunc(target)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockPanedWidget_ComputePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputePoint'
type MockPanedWidget_ComputePoint_Call struct {
	*mock.Call
}

// ComputePoint is a helper method to define mock.On call
//   - target layout.Widget
func (_e *MockPanedWidget_Expecter) ComputePoint(target interface{}) *MockPanedWidget_ComputePoint_Call {
	return &MockPanedWidget_ComputePoint_Call{Call: _e.mock.On("ComputePoint", target)}
}

func (_c *MockPanedWidget_ComputePoint_Call) Run(run func(target layout.Widget)) *MockPanedWidget_ComputePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Widget
		if args[0] != nil {
			arg0 = args[0].(layout.Widget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_ComputePoint_Call) Return(x float64, y float64, ok bool) *MockPanedWidget_ComputePoint_Call {
	_c.Call.Return(x, y, ok)
	return _c
}

func (_c *MockPanedWidget_ComputePoint_Call) RunAndReturn(run func(target layout.Widget) (float64, float64, bool)) *MockPanedWidget_ComputePoint_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectMap provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) ConnectMap(callback func()) uint32 {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for ConnectMap")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func(func()) uint32); ok {
		r0 = returnFunc(callback)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockPanedWidget_ConnectMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectMap'
type MockPanedWidget_ConnectMap_Call struct {
	*mock.Call
}

// ConnectMap is a helper method to define mock.On call
//   - callback func()
func (_e *MockPanedWidget_Expecter) ConnectMap(callback interface{}) *MockPanedWidget_ConnectMap_Call {
	return &MockPanedWidget_ConnectMap_Call{Call: _e.mock.On("ConnectMap", callback)}
}

func (_c *MockPanedWidget_ConnectMap_Call) Run(run func(callback func())) *MockPanedWidget_ConnectMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_ConnectMap_Call) Return(v uint32) *MockPanedWidget_ConnectMap_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPanedWidget_ConnectMap_Call) RunAndReturn(run func(callback func()) uint32) *MockPanedWidget_ConnectMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedHeight provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetAllocatedHeight() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedHeight")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPanedWidget_GetAllocatedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedHeight'
type MockPanedWidget_GetAllocatedHeight_Call struct {
	*mock.Call
}

// GetAllocatedHeight is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetAllocatedHeight() *MockPanedWidget_GetAllocatedHeight_Call {
	return &MockPanedWidget_GetAllocatedHeight_Call{Call: _e.mock.On("GetAllocatedHeight")}
}

func (_c *MockPanedWidget_GetAllocatedHeight_Call) Run(run func()) *MockPanedWidget_GetAllocatedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetAllocatedHeight_Call) Return(n int) *MockPanedWidget_GetAllocatedHeight_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPanedWidget_GetAllocatedHeight_Call) RunAndReturn(run func() int) *MockPanedWidget_GetAllocatedHeight_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedWidth provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetAllocatedWidth() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedWidth")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPanedWidget_GetAllocatedWidth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedWidth'
type MockPanedWidget_GetAllocatedWidth_Call struct {
	*mock.Call
}

// GetAllocatedWidth is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetAllocatedWidth() *MockPanedWidget_GetAllocatedWidth_Call {
	return &MockPanedWidget_GetAllocatedWidth_Call{Call: _e.mock.On("GetAllocatedWidth")}
}

func (_c *MockPanedWidget_GetAllocatedWidth_Call) Run(run func()) *MockPanedWidget_GetAllocatedWidth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetAllocatedWidth_Call) Return(n int) *MockPanedWidget_GetAllocatedWidth_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPanedWidget_GetAllocatedWidth_Call) RunAndReturn(run func() int) *MockPanedWidget_GetAllocatedWidth_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetEndChild() layout.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndChild")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockPanedWidget_GetEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndChild'
type MockPanedWidget_GetEndChild_Call struct {
	*mock.Call
}

// GetEndChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetEndChild() *MockPanedWidget_GetEndChild_Call {
	return &MockPanedWidget_GetEndChild_Call{Call: _e.mock.On("GetEndChild")}
}

func (_c *MockPanedWidget_GetEndChild_Call) Run(run func()) *MockPanedWidget_GetEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetEndChild_Call) Return(widget layout.Widget) *MockPanedWidget_GetEndChild_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockPanedWidget_GetEndChild_Call) RunAndReturn(run func() layout.Widget) *MockPanedWidget_GetEndChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetHexpand provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetHexpand() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHexpand")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHexpand'
type MockPanedWidget_GetHexpand_Call struct {
	*mock.Call
}

// GetHexpand is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetHexpand() *MockPanedWidget_GetHexpand_Call {
	return &MockPanedWidget_GetHexpand_Call{Call: _e.mock.On("GetHexpand")}
}

func (_c *MockPanedWidget_GetHexpand_Call) Run(run func()) *MockPanedWidget_GetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetHexpand_Call) Return(b bool) *MockPanedWidget_GetHexpand_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetHexpand_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetHexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GetParent provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetParent() layout.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockPanedWidget_GetParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParent'
type MockPanedWidget_GetParent_Call struct {
	*mock.Call
}

// GetParent is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetParent() *MockPanedWidget_GetParent_Call {
	return &MockPanedWidget_GetParent_Call{Call: _e.mock.On("GetParent")}
}

func (_c *MockPanedWidget_GetParent_Call) Run(run func()) *MockPanedWidget_GetParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetParent_Call) Return(widget layout.Widget) *MockPanedWidget_GetParent_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockPanedWidget_GetParent_Call) RunAndReturn(run func() layout.Widget) *MockPanedWidget_GetParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosition provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetPosition() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPanedWidget_GetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosition'
type MockPanedWidget_GetPosition_Call struct {
	*mock.Call
}

// GetPosition is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetPosition() *MockPanedWidget_GetPosition_Call {
	return &MockPanedWidget_GetPosition_Call{Call: _e.mock.On("GetPosition")}
}

func (_c *MockPanedWidget_GetPosition_Call) Run(run func()) *MockPanedWidget_GetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetPosition_Call) Return(n int) *MockPanedWidget_GetPosition_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPanedWidget_GetPosition_Call) RunAndReturn(run func() int) *MockPanedWidget_GetPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetResizeEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetResizeEndChild() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResizeEndChild")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetResizeEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResizeEndChild'
type MockPanedWidget_GetResizeEndChild_Call struct {
	*mock.Call
}

// GetResizeEndChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetResizeEndChild() *MockPanedWidget_GetResizeEndChild_Call {
	return &MockPanedWidget_GetResizeEndChild_Call{Call: _e.mock.On("GetResizeEndChild")}
}

func (_c *MockPanedWidget_GetResizeEndChild_Call) Run(run func()) *MockPanedWidget_GetResizeEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetResizeEndChild_Call) Return(b bool) *MockPanedWidget_GetResizeEndChild_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetResizeEndChild_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetResizeEndChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetResizeStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetResizeStartChild() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResizeStartChild")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetResizeStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResizeStartChild'
type MockPanedWidget_GetResizeStartChild_Call struct {
	*mock.Call
}

// GetResizeStartChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetResizeStartChild() *MockPanedWidget_GetResizeStartChild_Call {
	return &MockPanedWidget_GetResizeStartChild_Call{Call: _e.mock.On("GetResizeStartChild")}
}

func (_c *MockPanedWidget_GetResizeStartChild_Call) Run(run func()) *MockPanedWidget_GetResizeStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetResizeStartChild_Call) Return(b bool) *MockPanedWidget_GetResizeStartChild_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetResizeStartChild_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetResizeStartChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetShrinkEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetShrinkEndChild() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShrinkEndChild")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetShrinkEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShrinkEndChild'
type MockPanedWidget_GetShrinkEndChild_Call struct {
	*mock.Call
}

// GetShrinkEndChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetShrinkEndChild() *MockPanedWidget_GetShrinkEndChild_Call {
	return &MockPanedWidget_GetShrinkEndChild_Call{Call: _e.mock.On("GetShrinkEndChild")}
}

func (_c *MockPanedWidget_GetShrinkEndChild_Call) Run(run func()) *MockPanedWidget_GetShrinkEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetShrinkEndChild_Call) Return(b bool) *MockPanedWidget_GetShrinkEndChild_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetShrinkEndChild_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetShrinkEndChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetShrinkStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetShrinkStartChild() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShrinkStartChild")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetShrinkStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShrinkStartChild'
type MockPanedWidget_GetShrinkStartChild_Call struct {
	*mock.Call
}

// GetShrinkStartChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetShrinkStartChild() *MockPanedWidget_GetShrinkStartChild_Call {
	return &MockPanedWidget_GetShrinkStartChild_Call{Call: _e.mock.On("GetShrinkStartChild")}
}

func (_c *MockPanedWidget_GetShrinkStartChild_Call) Run(run func()) *MockPanedWidget_GetShrinkStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetShrinkStartChild_Call) Return(b bool) *MockPanedWidget_GetShrinkStartChild_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetShrinkStartChild_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetShrinkStartChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetStartChild() layout.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStartChild")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockPanedWidget_GetStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStartChild'
type MockPanedWidget_GetStartChild_Call struct {
	*mock.Call
}

// GetStartChild is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetStartChild() *MockPanedWidget_GetStartChild_Call {
	return &MockPanedWidget_GetStartChild_Call{Call: _e.mock.On("GetStartChild")}
}

func (_c *MockPanedWidget_GetStartChild_Call) Run(run func()) *MockPanedWidget_GetStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetStartChild_Call) Return(widget layout.Widget) *MockPanedWidget_GetStartChild_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockPanedWidget_GetStartChild_Call) RunAndReturn(run func() layout.Widget) *MockPanedWidget_GetStartChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetVexpand provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetVexpand() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVexpand")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVexpand'
type MockPanedWidget_GetVexpand_Call struct {
	*mock.Call
}

// GetVexpand is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetVexpand() *MockPanedWidget_GetVexpand_Call {
	return &MockPanedWidget_GetVexpand_Call{Call: _e.mock.On("GetVexpand")}
}

func (_c *MockPanedWidget_GetVexpand_Call) Run(run func()) *MockPanedWidget_GetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetVexpand_Call) Return(b bool) *MockPanedWidget_GetVexpand_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetVexpand_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetVexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GetWideHandle provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GetWideHandle() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWideHandle")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GetWideHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWideHandle'
type MockPanedWidget_GetWideHandle_Call struct {
	*mock.Call
}

// GetWideHandle is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GetWideHandle() *MockPanedWidget_GetWideHandle_Call {
	return &MockPanedWidget_GetWideHandle_Call{Call: _e.mock.On("GetWideHandle")}
}

func (_c *MockPanedWidget_GetWideHandle_Call) Run(run func()) *MockPanedWidget_GetWideHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GetWideHandle_Call) Return(b bool) *MockPanedWidget_GetWideHandle_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GetWideHandle_Call) RunAndReturn(run func() bool) *MockPanedWidget_GetWideHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GrabFocus provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GrabFocus() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GrabFocus")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_GrabFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrabFocus'
type MockPanedWidget_GrabFocus_Call struct {
	*mock.Call
}

// GrabFocus is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GrabFocus() *MockPanedWidget_GrabFocus_Call {
	return &MockPanedWidget_GrabFocus_Call{Call: _e.mock.On("GrabFocus")}
}

func (_c *MockPanedWidget_GrabFocus_Call) Run(run func()) *MockPanedWidget_GrabFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GrabFocus_Call) Return(b bool) *MockPanedWidget_GrabFocus_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_GrabFocus_Call) RunAndReturn(run func() bool) *MockPanedWidget_GrabFocus_Call {
	_c.Call.Return(run)
	return _c
}

// GtkWidget provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) GtkWidget() *gtk.Widget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GtkWidget")
	}

	var r0 *gtk.Widget
	if returnFunc, ok := ret.Get(0).(func() *gtk.Widget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gtk.Widget)
		}
	}
	return r0
}

// MockPanedWidget_GtkWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GtkWidget'
type MockPanedWidget_GtkWidget_Call struct {
	*mock.Call
}

// GtkWidget is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) GtkWidget() *MockPanedWidget_GtkWidget_Call {
	return &MockPanedWidget_GtkWidget_Call{Call: _e.mock.On("GtkWidget")}
}

func (_c *MockPanedWidget_GtkWidget_Call) Run(run func()) *MockPanedWidget_GtkWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_GtkWidget_Call) Return(widget *gtk.Widget) *MockPanedWidget_GtkWidget_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockPanedWidget_GtkWidget_Call) RunAndReturn(run func() *gtk.Widget) *MockPanedWidget_GtkWidget_Call {
	_c.Call.Return(run)
	return _c
}

// HasCssClass provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) HasCssClass(cssClass string) bool {
	ret := _mock.Called(cssClass)

	if len(ret) == 0 {
		panic("no return value specified for HasCssClass")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(cssClass)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_HasCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCssClass'
type MockPanedWidget_HasCssClass_Call struct {
	*mock.Call
}

// HasCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockPanedWidget_Expecter) HasCssClass(cssClass interface{}) *MockPanedWidget_HasCssClass_Call {
	return &MockPanedWidget_HasCssClass_Call{Call: _e.mock.On("HasCssClass", cssClass)}
}

func (_c *MockPanedWidget_HasCssClass_Call) Run(run func(cssClass string)) *MockPanedWidget_HasCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_HasCssClass_Call) Return(b bool) *MockPanedWidget_HasCssClass_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_HasCssClass_Call) RunAndReturn(run func(cssClass string) bool) *MockPanedWidget_HasCssClass_Call {
	_c.Call.Return(run)
	return _c
}

// HasFocus provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) HasFocus() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasFocus")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_HasFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFocus'
type MockPanedWidget_HasFocus_Call struct {
	*mock.Call
}

// HasFocus is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) HasFocus() *MockPanedWidget_HasFocus_Call {
	return &MockPanedWidget_HasFocus_Call{Call: _e.mock.On("HasFocus")}
}

func (_c *MockPanedWidget_HasFocus_Call) Run(run func()) *MockPanedWidget_HasFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_HasFocus_Call) Return(b bool) *MockPanedWidget_HasFocus_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_HasFocus_Call) RunAndReturn(run func() bool) *MockPanedWidget_HasFocus_Call {
	_c.Call.Return(run)
	return _c
}

// Hide provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) Hide() {
	_mock.Called()
	return
}

// MockPanedWidget_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type MockPanedWidget_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) Hide() *MockPanedWidget_Hide_Call {
	return &MockPanedWidget_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *MockPanedWidget_Hide_Call) Run(run func()) *MockPanedWidget_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_Hide_Call) Return() *MockPanedWidget_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_Hide_Call) RunAndReturn(run func()) *MockPanedWidget_Hide_Call {
	_c.Run(run)
	return _c
}

// IsVisible provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) IsVisible() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsVisible")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPanedWidget_IsVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVisible'
type MockPanedWidget_IsVisible_Call struct {
	*mock.Call
}

// IsVisible is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) IsVisible() *MockPanedWidget_IsVisible_Call {
	return &MockPanedWidget_IsVisible_Call{Call: _e.mock.On("IsVisible")}
}

func (_c *MockPanedWidget_IsVisible_Call) Run(run func()) *MockPanedWidget_IsVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_IsVisible_Call) Return(b bool) *MockPanedWidget_IsVisible_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPanedWidget_IsVisible_Call) RunAndReturn(run func() bool) *MockPanedWidget_IsVisible_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCssClass provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) RemoveCssClass(cssClass string) {
	_mock.Called(cssClass)
	return
}

// MockPanedWidget_RemoveCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCssClass'
type MockPanedWidget_RemoveCssClass_Call struct {
	*mock.Call
}

// RemoveCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockPanedWidget_Expecter) RemoveCssClass(cssClass interface{}) *MockPanedWidget_RemoveCssClass_Call {
	return &MockPanedWidget_RemoveCssClass_Call{Call: _e.mock.On("RemoveCssClass", cssClass)}
}

func (_c *MockPanedWidget_RemoveCssClass_Call) Run(run func(cssClass string)) *MockPanedWidget_RemoveCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_RemoveCssClass_Call) Return() *MockPanedWidget_RemoveCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_RemoveCssClass_Call) RunAndReturn(run func(cssClass string)) *MockPanedWidget_RemoveCssClass_Call {
	_c.Run(run)
	return _c
}

// SetCanFocus provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetCanFocus(canFocus bool) {
	_mock.Called(canFocus)
	return
}

// MockPanedWidget_SetCanFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanFocus'
type MockPanedWidget_SetCanFocus_Call struct {
	*mock.Call
}

// SetCanFocus is a helper method to define mock.On call
//   - canFocus bool
func (_e *MockPanedWidget_Expecter) SetCanFocus(canFocus interface{}) *MockPanedWidget_SetCanFocus_Call {
	return &MockPanedWidget_SetCanFocus_Call{Call: _e.mock.On("SetCanFocus", canFocus)}
}

func (_c *MockPanedWidget_SetCanFocus_Call) Run(run func(canFocus bool)) *MockPanedWidget_SetCanFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetCanFocus_Call) Return() *MockPanedWidget_SetCanFocus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetCanFocus_Call) RunAndReturn(run func(canFocus bool)) *MockPanedWidget_SetCanFocus_Call {
	_c.Run(run)
	return _c
}

// SetCanTarget provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetCanTarget(canTarget bool) {
	_mock.Called(canTarget)
	return
}

// MockPanedWidget_SetCanTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanTarget'
type MockPanedWidget_SetCanTarget_Call struct {
	*mock.Call
}

// SetCanTarget is a helper method to define mock.On call
//   - canTarget bool
func (_e *MockPanedWidget_Expecter) SetCanTarget(canTarget interface{}) *MockPanedWidget_SetCanTarget_Call {
	return &MockPanedWidget_SetCanTarget_Call{Call: _e.mock.On("SetCanTarget", canTarget)}
}

func (_c *MockPanedWidget_SetCanTarget_Call) Run(run func(canTarget bool)) *MockPanedWidget_SetCanTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetCanTarget_Call) Return() *MockPanedWidget_SetCanTarget_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetCanTarget_Call) RunAndReturn(run func(canTarget bool)) *MockPanedWidget_SetCanTarget_Call {
	_c.Run(run)
	return _c
}

// SetEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetEndChild(child layout.Widget) {
	_mock.Called(child)
	return
}

// MockPanedWidget_SetEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEndChild'
type MockPanedWidget_SetEndChild_Call struct {
	*mock.Call
}

// SetEndChild is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockPanedWidget_Expecter) SetEndChild(child interface{}) *MockPanedWidget_SetEndChild_Call {
	return &MockPanedWidget_SetEndChild_Call{Call: _e.mock.On("SetEndChild", child)}
}

func (_c *MockPanedWidget_SetEndChild_Call) Run(run func(child layout.Widget)) *MockPanedWidget_SetEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Widget
		if args[0] != nil {
			arg0 = args[0].(layout.Widget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetEndChild_Call) Return() *MockPanedWidget_SetEndChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetEndChild_Call) RunAndReturn(run func(child layout.Widget)) *MockPanedWidget_SetEndChild_Call {
	_c.Run(run)
	return _c
}

// SetFocusOnClick provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetFocusOnClick(focusOnClick bool) {
	_mock.Called(focusOnClick)
	return
}

// MockPanedWidget_SetFocusOnClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFocusOnClick'
type MockPanedWidget_SetFocusOnClick_Call struct {
	*mock.Call
}

// SetFocusOnClick is a helper method to define mock.On call
//   - focusOnClick bool
func (_e *MockPanedWidget_Expecter) SetFocusOnClick(focusOnClick interface{}) *MockPanedWidget_SetFocusOnClick_Call {
	return &MockPanedWidget_SetFocusOnClick_Call{Call: _e.mock.On("SetFocusOnClick", focusOnClick)}
}

func (_c *MockPanedWidget_SetFocusOnClick_Call) Run(run func(focusOnClick bool)) *MockPanedWidget_SetFocusOnClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetFocusOnClick_Call) Return() *MockPanedWidget_SetFocusOnClick_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetFocusOnClick_Call) RunAndReturn(run func(focusOnClick bool)) *MockPanedWidget_SetFocusOnClick_Call {
	_c.Run(run)
	return _c
}

// SetHalign provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetHalign(align gtk.Align) {
	_mock.Called(align)
	return
}

// MockPanedWidget_SetHalign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHalign'
type MockPanedWidget_SetHalign_Call struct {
	*mock.Call
}

// SetHalign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockPanedWidget_Expecter) SetHalign(align interface{}) *MockPanedWidget_SetHalign_Call {
	return &MockPanedWidget_SetHalign_Call{Call: _e.mock.On("SetHalign", align)}
}

func (_c *MockPanedWidget_SetHalign_Call) Run(run func(align gtk.Align)) *MockPanedWidget_SetHalign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gtk.Align
		if args[0] != nil {
			arg0 = args[0].(gtk.Align)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetHalign_Call) Return() *MockPanedWidget_SetHalign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetHalign_Call) RunAndReturn(run func(align gtk.Align)) *MockPanedWidget_SetHalign_Call {
	_c.Run(run)
	return _c
}

// SetHexpand provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetHexpand(expand bool) {
	_mock.Called(expand)
	return
}

// MockPanedWidget_SetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHexpand'
type MockPanedWidget_SetHexpand_Call struct {
	*mock.Call
}

// SetHexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockPanedWidget_Expecter) SetHexpand(expand interface{}) *MockPanedWidget_SetHexpand_Call {
	return &MockPanedWidget_SetHexpand_Call{Call: _e.mock.On("SetHexpand", expand)}
}

func (_c *MockPanedWidget_SetHexpand_Call) Run(run func(expand bool)) *MockPanedWidget_SetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetHexpand_Call) Return() *MockPanedWidget_SetHexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetHexpand_Call) RunAndReturn(run func(expand bool)) *MockPanedWidget_SetHexpand_Call {
	_c.Run(run)
	return _c
}

// SetPosition provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetPosition(position int) {
	_mock.Called(position)
	return
}

// MockPanedWidget_SetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPosition'
type MockPanedWidget_SetPosition_Call struct {
	*mock.Call
}

// SetPosition is a helper method to define mock.On call
//   - position int
func (_e *MockPanedWidget_Expecter) SetPosition(position interface{}) *MockPanedWidget_SetPosition_Call {
	return &MockPanedWidget_SetPosition_Call{Call: _e.mock.On("SetPosition", position)}
}

func (_c *MockPanedWidget_SetPosition_Call) Run(run func(position int)) *MockPanedWidget_SetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetPosition_Call) Return() *MockPanedWidget_SetPosition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetPosition_Call) RunAndReturn(run func(position int)) *MockPanedWidget_SetPosition_Call {
	_c.Run(run)
	return _c
}

// SetResizeEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetResizeEndChild(resize bool) {
	_mock.Called(resize)
	return
}

// MockPanedWidget_SetResizeEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResizeEndChild'
type MockPanedWidget_SetResizeEndChild_Call struct {
	*mock.Call
}

// SetResizeEndChild is a helper method to define mock.On call
//   - resize bool
func (_e *MockPanedWidget_Expecter) SetResizeEndChild(resize interface{}) *MockPanedWidget_SetResizeEndChild_Call {
	return &MockPanedWidget_SetResizeEndChild_Call{Call: _e.mock.On("SetResizeEndChild", resize)}
}

func (_c *MockPanedWidget_SetResizeEndChild_Call) Run(run func(resize bool)) *MockPanedWidget_SetResizeEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetResizeEndChild_Call) Return() *MockPanedWidget_SetResizeEndChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetResizeEndChild_Call) RunAndReturn(run func(resize bool)) *MockPanedWidget_SetResizeEndChild_Call {
	_c.Run(run)
	return _c
}

// SetResizeStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetResizeStartChild(resize bool) {
	_mock.Called(resize)
	return
}

// MockPanedWidget_SetResizeStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResizeStartChild'
type MockPanedWidget_SetResizeStartChild_Call struct {
	*mock.Call
}

// SetResizeStartChild is a helper method to define mock.On call
//   - resize bool
func (_e *MockPanedWidget_Expecter) SetResizeStartChild(resize interface{}) *MockPanedWidget_SetResizeStartChild_Call {
	return &MockPanedWidget_SetResizeStartChild_Call{Call: _e.mock.On("SetResizeStartChild", resize)}
}

func (_c *MockPanedWidget_SetResizeStartChild_Call) Run(run func(resize bool)) *MockPanedWidget_SetResizeStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetResizeStartChild_Call) Return() *MockPanedWidget_SetResizeStartChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetResizeStartChild_Call) RunAndReturn(run func(resize bool)) *MockPanedWidget_SetResizeStartChild_Call {
	_c.Run(run)
	return _c
}

// SetShrinkEndChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetShrinkEndChild(shrink bool) {
	_mock.Called(shrink)
	return
}

// MockPanedWidget_SetShrinkEndChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShrinkEndChild'
type MockPanedWidget_SetShrinkEndChild_Call struct {
	*mock.Call
}

// SetShrinkEndChild is a helper method to define mock.On call
//   - shrink bool
func (_e *MockPanedWidget_Expecter) SetShrinkEndChild(shrink interface{}) *MockPanedWidget_SetShrinkEndChild_Call {
	return &MockPanedWidget_SetShrinkEndChild_Call{Call: _e.mock.On("SetShrinkEndChild", shrink)}
}

func (_c *MockPanedWidget_SetShrinkEndChild_Call) Run(run func(shrink bool)) *MockPanedWidget_SetShrinkEndChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetShrinkEndChild_Call) Return() *MockPanedWidget_SetShrinkEndChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetShrinkEndChild_Call) RunAndReturn(run func(shrink bool)) *MockPanedWidget_SetShrinkEndChild_Call {
	_c.Run(run)
	return _c
}

// SetShrinkStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetShrinkStartChild(shrink bool) {
	_mock.Called(shrink)
	return
}

// MockPanedWidget_SetShrinkStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShrinkStartChild'
type MockPanedWidget_SetShrinkStartChild_Call struct {
	*mock.Call
}

// SetShrinkStartChild is a helper method to define mock.On call
//   - shrink bool
func (_e *MockPanedWidget_Expecter) SetShrinkStartChild(shrink interface{}) *MockPanedWidget_SetShrinkStartChild_Call {
	return &MockPanedWidget_SetShrinkStartChild_Call{Call: _e.mock.On("SetShrinkStartChild", shrink)}
}

func (_c *MockPanedWidget_SetShrinkStartChild_Call) Run(run func(shrink bool)) *MockPanedWidget_SetShrinkStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetShrinkStartChild_Call) Return() *MockPanedWidget_SetShrinkStartChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetShrinkStartChild_Call) RunAndReturn(run func(shrink bool)) *MockPanedWidget_SetShrinkStartChild_Call {
	_c.Run(run)
	return _c
}

// SetSizeRequest provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetSizeRequest(width int, height int) {
	_mock.Called(width, height)
	return
}

// MockPanedWidget_SetSizeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSizeRequest'
type MockPanedWidget_SetSizeRequest_Call struct {
	*mock.Call
}

// SetSizeRequest is a helper method to define mock.On call
//   - width int
//   - height int
func (_e *MockPanedWidget_Expecter) SetSizeRequest(width interface{}, height interface{}) *MockPanedWidget_SetSizeRequest_Call {
	return &MockPanedWidget_SetSizeRequest_Call{Call: _e.mock.On("SetSizeRequest", width, height)}
}

func (_c *MockPanedWidget_SetSizeRequest_Call) Run(run func(width int, height int)) *MockPanedWidget_SetSizeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetSizeRequest_Call) Return() *MockPanedWidget_SetSizeRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetSizeRequest_Call) RunAndReturn(run func(width int, height int)) *MockPanedWidget_SetSizeRequest_Call {
	_c.Run(run)
	return _c
}

// SetStartChild provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetStartChild(child layout.Widget) {
	_mock.Called(child)
	return
}

// MockPanedWidget_SetStartChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStartChild'
type MockPanedWidget_SetStartChild_Call struct {
	*mock.Call
}

// SetStartChild is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockPanedWidget_Expecter) SetStartChild(child interface{}) *MockPanedWidget_SetStartChild_Call {
	return &MockPanedWidget_SetStartChild_Call{Call: _e.mock.On("SetStartChild", child)}
}

func (_c *MockPanedWidget_SetStartChild_Call) Run(run func(child layout.Widget)) *MockPanedWidget_SetStartChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Widget
		if args[0] != nil {
			arg0 = args[0].(layout.Widget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetStartChild_Call) Return() *MockPanedWidget_SetStartChild_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetStartChild_Call) RunAndReturn(run func(child layout.Widget)) *MockPanedWidget_SetStartChild_Call {
	_c.Run(run)
	return _c
}

// SetValign provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetValign(align gtk.Align) {
	_mock.Called(align)
	return
}

// MockPanedWidget_SetValign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValign'
type MockPanedWidget_SetValign_Call struct {
	*mock.Call
}

// SetValign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockPanedWidget_Expecter) SetValign(align interface{}) *MockPanedWidget_SetValign_Call {
	return &MockPanedWidget_SetValign_Call{Call: _e.mock.On("SetValign", align)}
}

func (_c *MockPanedWidget_SetValign_Call) Run(run func(align gtk.Align)) *MockPanedWidget_SetValign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gtk.Align
		if args[0] != nil {
			arg0 = args[0].(gtk.Align)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetValign_Call) Return() *MockPanedWidget_SetValign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetValign_Call) RunAndReturn(run func(align gtk.Align)) *MockPanedWidget_SetValign_Call {
	_c.Run(run)
	return _c
}

// SetVexpand provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetVexpand(expand bool) {
	_mock.Called(expand)
	return
}

// MockPanedWidget_SetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVexpand'
type MockPanedWidget_SetVexpand_Call struct {
	*mock.Call
}

// SetVexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockPanedWidget_Expecter) SetVexpand(expand interface{}) *MockPanedWidget_SetVexpand_Call {
	return &MockPanedWidget_SetVexpand_Call{Call: _e.mock.On("SetVexpand", expand)}
}

func (_c *MockPanedWidget_SetVexpand_Call) Run(run func(expand bool)) *MockPanedWidget_SetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetVexpand_Call) Return() *MockPanedWidget_SetVexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetVexpand_Call) RunAndReturn(run func(expand bool)) *MockPanedWidget_SetVexpand_Call {
	_c.Run(run)
	return _c
}

// SetVisible provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetVisible(visible bool) {
	_mock.Called(visible)
	return
}

// MockPanedWidget_SetVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVisible'
type MockPanedWidget_SetVisible_Call struct {
	*mock.Call
}

// SetVisible is a helper method to define mock.On call
//   - visible bool
func (_e *MockPanedWidget_Expecter) SetVisible(visible interface{}) *MockPanedWidget_SetVisible_Call {
	return &MockPanedWidget_SetVisible_Call{Call: _e.mock.On("SetVisible", visible)}
}

func (_c *MockPanedWidget_SetVisible_Call) Run(run func(visible bool)) *MockPanedWidget_SetVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetVisible_Call) Return() *MockPanedWidget_SetVisible_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetVisible_Call) RunAndReturn(run func(visible bool)) *MockPanedWidget_SetVisible_Call {
	_c.Run(run)
	return _c
}

// SetWideHandle provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) SetWideHandle(wide bool) {
	_mock.Called(wide)
	return
}

// MockPanedWidget_SetWideHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWideHandle'
type MockPanedWidget_SetWideHandle_Call struct {
	*mock.Call
}

// SetWideHandle is a helper method to define mock.On call
//   - wide bool
func (_e *MockPanedWidget_Expecter) SetWideHandle(wide interface{}) *MockPanedWidget_SetWideHandle_Call {
	return &MockPanedWidget_SetWideHandle_Call{Call: _e.mock.On("SetWideHandle", wide)}
}

func (_c *MockPanedWidget_SetWideHandle_Call) Run(run func(wide bool)) *MockPanedWidget_SetWideHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPanedWidget_SetWideHandle_Call) Return() *MockPanedWidget_SetWideHandle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_SetWideHandle_Call) RunAndReturn(run func(wide bool)) *MockPanedWidget_SetWideHandle_Call {
	_c.Run(run)
	return _c
}

// Show provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) Show() {
	_mock.Called()
	return
}

// MockPanedWidget_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockPanedWidget_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) Show() *MockPanedWidget_Show_Call {
	return &MockPanedWidget_Show_Call{Call: _e.mock.On("Show")}
}

func (_c *MockPanedWidget_Show_Call) Run(run func()) *MockPanedWidget_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_Show_Call) Return() *MockPanedWidget_Show_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_Show_Call) RunAndReturn(run func()) *MockPanedWidget_Show_Call {
	_c.Run(run)
	return _c
}

// Unparent provides a mock function for the type MockPanedWidget
func (_mock *MockPanedWidget) Unparent() {
	_mock.Called()
	return
}

// MockPanedWidget_Unparent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unparent'
type MockPanedWidget_Unparent_Call struct {
	*mock.Call
}

// Unparent is a helper method to define mock.On call
func (_e *MockPanedWidget_Expecter) Unparent() *MockPanedWidget_Unparent_Call {
	return &MockPanedWidget_Unparent_Call{Call: _e.mock.On("Unparent")}
}

func (_c *MockPanedWidget_Unparent_Call) Run(run func()) *MockPanedWidget_Unparent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPanedWidget_Unparent_Call) Return() *MockPanedWidget_Unparent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPanedWidget_Unparent_Call) RunAndReturn(run func()) *MockPanedWidget_Unparent_Call {
	_c.Run(run)
	return _c
}
