// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/dumber/internal/ui/layout"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaneRenderer creates a new instance of MockPaneRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaneRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaneRenderer {
	mock := &MockPaneRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaneRenderer is an autogenerated mock type for the PaneRenderer type
type MockPaneRenderer struct {
	mock.Mock
}

type MockPaneRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaneRenderer) EXPECT() *MockPaneRenderer_Expecter {
	return &MockPaneRenderer_Expecter{mock: &_m.Mock}
}

// RenderPane provides a mock function for the type MockPaneRenderer
func (_mock *MockPaneRenderer) RenderPane(paneID string, webViewWidget layout.Widget) layout.Widget {
	ret := _mock.Called(paneID, webViewWidget)

	if len(ret) == 0 {
		panic("no return value specified for RenderPane")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func(string, layout.Widget) layout.Widget); ok {
		r0 = returnFunc(paneID, webViewWidget)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockPaneRenderer_RenderPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderPane'
type MockPaneRenderer_RenderPane_Call struct {
	*mock.Call
}

// RenderPane is a helper method to define mock.On call
//   - paneID string
//   - webViewWidget layout.Widget
func (_e *MockPaneRenderer_Expecter) RenderPane(paneID interface{}, webViewWidget interface{}) *MockPaneRenderer_RenderPane_Call {
	return &MockPaneRenderer_RenderPane_Call{Call: _e.mock.On("RenderPane", paneID, webViewWidget)}
}

func (_c *MockPaneRenderer_RenderPane_Call) Run(run func(paneID string, webViewWidget layout.Widget)) *MockPaneRenderer_RenderPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 layout.Widget
		if args[1] != nil {
			arg1 = args[1].(layout.Widget)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaneRenderer_RenderPane_Call) Return(widget layout.Widget) *MockPaneRenderer_RenderPane_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockPaneRenderer_RenderPane_Call) RunAndReturn(run func(paneID string, webViewWidget layout.Widget) layout.Widget) *MockPaneRenderer_RenderPane_Call {
	_c.Call.Return(run)
	return _c
}
