// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/dumber/internal/ui/layout"
	"github.com/jwijenbergh/puregotk/v4/gtk"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWidgetFactory creates a new instance of MockWidgetFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWidgetFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWidgetFactory {
	mock := &MockWidgetFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWidgetFactory is an autogenerated mock type for the WidgetFactory type
type MockWidgetFactory struct {
	mock.Mock
}

type MockWidgetFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWidgetFactory) EXPECT() *MockWidgetFactory_Expecter {
	return &MockWidgetFactory_Expecter{mock: &_m.Mock}
}

// NewBox provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewBox(orientation layout.Orientation, spacing int) layout.BoxWidget {
	ret := _mock.Called(orientation, spacing)

	if len(ret) == 0 {
		panic("no return value specified for NewBox")
	}

	var r0 layout.BoxWidget
	if returnFunc, ok := ret.Get(0).(func(layout.Orientation, int) layout.BoxWidget); ok {
		r0 = returnFunc(orientation, spacing)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.BoxWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewBox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBox'
type MockWidgetFactory_NewBox_Call struct {
	*mock.Call
}

// NewBox is a helper method to define mock.On call
//   - orientation layout.Orientation
//   - spacing int
func (_e *MockWidgetFactory_Expecter) NewBox(orientation interface{}, spacing interface{}) *MockWidgetFactory_NewBox_Call {
	return &MockWidgetFactory_NewBox_Call{Call: _e.mock.On("NewBox", orientation, spacing)}
}

func (_c *MockWidgetFactory_NewBox_Call) Run(run func(orientation layout.Orientation, spacing int)) *MockWidgetFactory_NewBox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Orientation
		if args[0] != nil {
			arg0 = args[0].(layout.Orientation)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWidgetFactory_NewBox_Call) Return(boxWidget layout.BoxWidget) *MockWidgetFactory_NewBox_Call {
	_c.Call.Return(boxWidget)
	return _c
}

func (_c *MockWidgetFactory_NewBox_Call) RunAndReturn(run func(orientation layout.Orientation, spacing int) layout.BoxWidget) *MockWidgetFactory_NewBox_Call {
	_c.Call.Return(run)
	return _c
}

// NewButton provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewButton() layout.ButtonWidget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewButton")
	}

	var r0 layout.ButtonWidget
	if returnFunc, ok := ret.Get(0).(func() layout.ButtonWidget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.ButtonWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewButton_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewButton'
type MockWidgetFactory_NewButton_Call struct {
	*mock.Call
}

// NewButton is a helper method to define mock.On call
func (_e *MockWidgetFactory_Expecter) NewButton() *MockWidgetFactory_NewButton_Call {
	return &MockWidgetFactory_NewButton_Call{Call: _e.mock.On("NewButton")}
}

func (_c *MockWidgetFactory_NewButton_Call) Run(run func()) *MockWidgetFactory_NewButton_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidgetFactory_NewButton_Call) Return(buttonWidget layout.ButtonWidget) *MockWidgetFactory_NewButton_Call {
	_c.Call.Return(buttonWidget)
	return _c
}

func (_c *MockWidgetFactory_NewButton_Call) RunAndReturn(run func() layout.ButtonWidget) *MockWidgetFactory_NewButton_Call {
	_c.Call.Return(run)
	return _c
}

// NewImage provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewImage() layout.ImageWidget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewImage")
	}

	var r0 layout.ImageWidget
	if returnFunc, ok := ret.Get(0).(func() layout.ImageWidget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.ImageWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewImage'
type MockWidgetFactory_NewImage_Call struct {
	*mock.Call
}

// NewImage is a helper method to define mock.On call
func (_e *MockWidgetFactory_Expecter) NewImage() *MockWidgetFactory_NewImage_Call {
	return &MockWidgetFactory_NewImage_Call{Call: _e.mock.On("NewImage")}
}

func (_c *MockWidgetFactory_NewImage_Call) Run(run func()) *MockWidgetFactory_NewImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidgetFactory_NewImage_Call) Return(imageWidget layout.ImageWidget) *MockWidgetFactory_NewImage_Call {
	_c.Call.Return(imageWidget)
	return _c
}

func (_c *MockWidgetFactory_NewImage_Call) RunAndReturn(run func() layout.ImageWidget) *MockWidgetFactory_NewImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewLabel provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewLabel(text string) layout.LabelWidget {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for NewLabel")
	}

	var r0 layout.LabelWidget
	if returnFunc, ok := ret.Get(0).(func(string) layout.LabelWidget); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.LabelWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewLabel'
type MockWidgetFactory_NewLabel_Call struct {
	*mock.Call
}

// NewLabel is a helper method to define mock.On call
//   - text string
func (_e *MockWidgetFactory_Expecter) NewLabel(text interface{}) *MockWidgetFactory_NewLabel_Call {
	return &MockWidgetFactory_NewLabel_Call{Call: _e.mock.On("NewLabel", text)}
}

func (_c *MockWidgetFactory_NewLabel_Call) Run(run func(text string)) *MockWidgetFactory_NewLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWidgetFactory_NewLabel_Call) Return(labelWidget layout.LabelWidget) *MockWidgetFactory_NewLabel_Call {
	_c.Call.Return(labelWidget)
	return _c
}

func (_c *MockWidgetFactory_NewLabel_Call) RunAndReturn(run func(text string) layout.LabelWidget) *MockWidgetFactory_NewLabel_Call {
	_c.Call.Return(run)
	return _c
}

// NewOverlay provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewOverlay() layout.OverlayWidget {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewOverlay")
	}

	var r0 layout.OverlayWidget
	if returnFunc, ok := ret.Get(0).(func() layout.OverlayWidget); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.OverlayWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewOverlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewOverlay'
type MockWidgetFactory_NewOverlay_Call struct {
	*mock.Call
}

// NewOverlay is a helper method to define mock.On call
func (_e *MockWidgetFactory_Expecter) NewOverlay() *MockWidgetFactory_NewOverlay_Call {
	return &MockWidgetFactory_NewOverlay_Call{Call: _e.mock.On("NewOverlay")}
}

func (_c *MockWidgetFactory_NewOverlay_Call) Run(run func()) *MockWidgetFactory_NewOverlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWidgetFactory_NewOverlay_Call) Return(overlayWidget layout.OverlayWidget) *MockWidgetFactory_NewOverlay_Call {
	_c.Call.Return(overlayWidget)
	return _c
}

func (_c *MockWidgetFactory_NewOverlay_Call) RunAndReturn(run func() layout.OverlayWidget) *MockWidgetFactory_NewOverlay_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaned provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) NewPaned(orientation layout.Orientation) layout.PanedWidget {
	ret := _mock.Called(orientation)

	if len(ret) == 0 {
		panic("no return value specified for NewPaned")
	}

	var r0 layout.PanedWidget
	if returnFunc, ok := ret.Get(0).(func(layout.Orientation) layout.PanedWidget); ok {
		r0 = returnFunc(orientation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.PanedWidget)
		}
	}
	return r0
}

// MockWidgetFactory_NewPaned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPaned'
type MockWidgetFactory_NewPaned_Call struct {
	*mock.Call
}

// NewPaned is a helper method to define mock.On call
//   - orientation layout.Orientation
func (_e *MockWidgetFactory_Expecter) NewPaned(orientation interface{}) *MockWidgetFactory_NewPaned_Call {
	return &MockWidgetFactory_NewPaned_Call{Call: _e.mock.On("NewPaned", orientation)}
}

func (_c *MockWidgetFactory_NewPaned_Call) Run(run func(orientation layout.Orientation)) *MockWidgetFactory_NewPaned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 layout.Orientation
		if args[0] != nil {
			arg0 = args[0].(layout.Orientation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWidgetFactory_NewPaned_Call) Return(panedWidget layout.PanedWidget) *MockWidgetFactory_NewPaned_Call {
	_c.Call.Return(panedWidget)
	return _c
}

func (_c *MockWidgetFactory_NewPaned_Call) RunAndReturn(run func(orientation layout.Orientation) layout.PanedWidget) *MockWidgetFactory_NewPaned_Call {
	_c.Call.Return(run)
	return _c
}

// WrapWidget provides a mock function for the type MockWidgetFactory
func (_mock *MockWidgetFactory) WrapWidget(w *gtk.Widget) layout.Widget {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for WrapWidget")
	}

	var r0 layout.Widget
	if returnFunc, ok := ret.Get(0).(func(*gtk.Widget) layout.Widget); ok {
		r0 = returnFunc(w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}
	return r0
}

// MockWidgetFactory_WrapWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapWidget'
type MockWidgetFactory_WrapWidget_Call struct {
	*mock.Call
}

// WrapWidget is a helper method to define mock.On call
//   - w *gtk.Widget
func (_e *MockWidgetFactory_Expecter) WrapWidget(w interface{}) *MockWidgetFactory_WrapWidget_Call {
	return &MockWidgetFactory_WrapWidget_Call{Call: _e.mock.On("WrapWidget", w)}
}

func (_c *MockWidgetFactory_WrapWidget_Call) Run(run func(w *gtk.Widget)) *MockWidgetFactory_WrapWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gtk.Widget
		if args[0] != nil {
			arg0 = args[0].(*gtk.Widget)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWidgetFactory_WrapWidget_Call) Return(widget layout.Widget) *MockWidgetFactory_WrapWidget_Call {
	_c.Call.Return(widget)
	return _c
}

func (_c *MockWidgetFactory_WrapWidget_Call) RunAndReturn(run func(w *gtk.Widget) layout.Widget) *MockWidgetFactory_WrapWidget_Call {
	_c.Call.Return(run)
	return _c
}
