// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "github.com/bnema/dumber/internal/domain/entity"
	layout "github.com/bnema/dumber/internal/ui/layout"

	mock "github.com/stretchr/testify/mock"
)

// MockPaneViewFactory is an autogenerated mock type for the PaneViewFactory type
type MockPaneViewFactory struct {
	mock.Mock
}

type MockPaneViewFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaneViewFactory) EXPECT() *MockPaneViewFactory_Expecter {
	return &MockPaneViewFactory_Expecter{mock: &_m.Mock}
}

// CreatePaneView provides a mock function with given fields: node
func (_m *MockPaneViewFactory) CreatePaneView(node *entity.PaneNode) layout.Widget {
	ret := _m.Called(node)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaneView")
	}

	var r0 layout.Widget
	if rf, ok := ret.Get(0).(func(*entity.PaneNode) layout.Widget); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}

	return r0
}

// MockPaneViewFactory_CreatePaneView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaneView'
type MockPaneViewFactory_CreatePaneView_Call struct {
	*mock.Call
}

// CreatePaneView is a helper method to define mock.On call
//   - node *entity.PaneNode
func (_e *MockPaneViewFactory_Expecter) CreatePaneView(node interface{}) *MockPaneViewFactory_CreatePaneView_Call {
	return &MockPaneViewFactory_CreatePaneView_Call{Call: _e.mock.On("CreatePaneView", node)}
}

func (_c *MockPaneViewFactory_CreatePaneView_Call) Run(run func(node *entity.PaneNode)) *MockPaneViewFactory_CreatePaneView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PaneNode))
	})
	return _c
}

func (_c *MockPaneViewFactory_CreatePaneView_Call) Return(_a0 layout.Widget) *MockPaneViewFactory_CreatePaneView_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaneViewFactory_CreatePaneView_Call) RunAndReturn(run func(*entity.PaneNode) layout.Widget) *MockPaneViewFactory_CreatePaneView_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaneViewFactory creates a new instance of MockPaneViewFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaneViewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaneViewFactory {
	mock := &MockPaneViewFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
