// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	layout "github.com/bnema/dumber/internal/ui/layout"
	gtk "github.com/jwijenbergh/puregotk/v4/gtk"

	mock "github.com/stretchr/testify/mock"
)

// MockBoxWidget is an autogenerated mock type for the BoxWidget type
type MockBoxWidget struct {
	mock.Mock
}

type MockBoxWidget_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoxWidget) EXPECT() *MockBoxWidget_Expecter {
	return &MockBoxWidget_Expecter{mock: &_m.Mock}
}

// AddController provides a mock function with given fields: controller
func (_m *MockBoxWidget) AddController(controller *gtk.EventController) {
	_m.Called(controller)
}

// MockBoxWidget_AddController_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddController'
type MockBoxWidget_AddController_Call struct {
	*mock.Call
}

// AddController is a helper method to define mock.On call
//   - controller *gtk.EventController
func (_e *MockBoxWidget_Expecter) AddController(controller interface{}) *MockBoxWidget_AddController_Call {
	return &MockBoxWidget_AddController_Call{Call: _e.mock.On("AddController", controller)}
}

func (_c *MockBoxWidget_AddController_Call) Run(run func(controller *gtk.EventController)) *MockBoxWidget_AddController_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gtk.EventController))
	})
	return _c
}

func (_c *MockBoxWidget_AddController_Call) Return() *MockBoxWidget_AddController_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_AddController_Call) RunAndReturn(run func(*gtk.EventController)) *MockBoxWidget_AddController_Call {
	_c.Run(run)
	return _c
}

// AddCssClass provides a mock function with given fields: cssClass
func (_m *MockBoxWidget) AddCssClass(cssClass string) {
	_m.Called(cssClass)
}

// MockBoxWidget_AddCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCssClass'
type MockBoxWidget_AddCssClass_Call struct {
	*mock.Call
}

// AddCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockBoxWidget_Expecter) AddCssClass(cssClass interface{}) *MockBoxWidget_AddCssClass_Call {
	return &MockBoxWidget_AddCssClass_Call{Call: _e.mock.On("AddCssClass", cssClass)}
}

func (_c *MockBoxWidget_AddCssClass_Call) Run(run func(cssClass string)) *MockBoxWidget_AddCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBoxWidget_AddCssClass_Call) Return() *MockBoxWidget_AddCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_AddCssClass_Call) RunAndReturn(run func(string)) *MockBoxWidget_AddCssClass_Call {
	_c.Run(run)
	return _c
}

// Append provides a mock function with given fields: child
func (_m *MockBoxWidget) Append(child layout.Widget) {
	_m.Called(child)
}

// MockBoxWidget_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockBoxWidget_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockBoxWidget_Expecter) Append(child interface{}) *MockBoxWidget_Append_Call {
	return &MockBoxWidget_Append_Call{Call: _e.mock.On("Append", child)}
}

func (_c *MockBoxWidget_Append_Call) Run(run func(child layout.Widget)) *MockBoxWidget_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_Append_Call) Return() *MockBoxWidget_Append_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Append_Call) RunAndReturn(run func(layout.Widget)) *MockBoxWidget_Append_Call {
	_c.Run(run)
	return _c
}

// ComputePoint provides a mock function with given fields: target
func (_m *MockBoxWidget) ComputePoint(target layout.Widget) (float64, float64, bool) {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for ComputePoint")
	}

	var r0 float64
	var r1 float64
	var r2 bool
	if rf, ok := ret.Get(0).(func(layout.Widget) (float64, float64, bool)); ok {
		return rf(target)
	}
	if rf, ok := ret.Get(0).(func(layout.Widget) float64); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(layout.Widget) float64); ok {
		r1 = rf(target)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(layout.Widget) bool); ok {
		r2 = rf(target)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockBoxWidget_ComputePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputePoint'
type MockBoxWidget_ComputePoint_Call struct {
	*mock.Call
}

// ComputePoint is a helper method to define mock.On call
//   - target layout.Widget
func (_e *MockBoxWidget_Expecter) ComputePoint(target interface{}) *MockBoxWidget_ComputePoint_Call {
	return &MockBoxWidget_ComputePoint_Call{Call: _e.mock.On("ComputePoint", target)}
}

func (_c *MockBoxWidget_ComputePoint_Call) Run(run func(target layout.Widget)) *MockBoxWidget_ComputePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_ComputePoint_Call) Return(x float64, y float64, ok bool) *MockBoxWidget_ComputePoint_Call {
	_c.Call.Return(x, y, ok)
	return _c
}

func (_c *MockBoxWidget_ComputePoint_Call) RunAndReturn(run func(layout.Widget) (float64, float64, bool)) *MockBoxWidget_ComputePoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedHeight provides a mock function with no fields
func (_m *MockBoxWidget) GetAllocatedHeight() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedHeight")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBoxWidget_GetAllocatedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedHeight'
type MockBoxWidget_GetAllocatedHeight_Call struct {
	*mock.Call
}

// GetAllocatedHeight is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetAllocatedHeight() *MockBoxWidget_GetAllocatedHeight_Call {
	return &MockBoxWidget_GetAllocatedHeight_Call{Call: _e.mock.On("GetAllocatedHeight")}
}

func (_c *MockBoxWidget_GetAllocatedHeight_Call) Run(run func()) *MockBoxWidget_GetAllocatedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetAllocatedHeight_Call) Return(_a0 int) *MockBoxWidget_GetAllocatedHeight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetAllocatedHeight_Call) RunAndReturn(run func() int) *MockBoxWidget_GetAllocatedHeight_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocatedWidth provides a mock function with no fields
func (_m *MockBoxWidget) GetAllocatedWidth() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatedWidth")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBoxWidget_GetAllocatedWidth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatedWidth'
type MockBoxWidget_GetAllocatedWidth_Call struct {
	*mock.Call
}

// GetAllocatedWidth is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetAllocatedWidth() *MockBoxWidget_GetAllocatedWidth_Call {
	return &MockBoxWidget_GetAllocatedWidth_Call{Call: _e.mock.On("GetAllocatedWidth")}
}

func (_c *MockBoxWidget_GetAllocatedWidth_Call) Run(run func()) *MockBoxWidget_GetAllocatedWidth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetAllocatedWidth_Call) Return(_a0 int) *MockBoxWidget_GetAllocatedWidth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetAllocatedWidth_Call) RunAndReturn(run func() int) *MockBoxWidget_GetAllocatedWidth_Call {
	_c.Call.Return(run)
	return _c
}

// GetHexpand provides a mock function with no fields
func (_m *MockBoxWidget) GetHexpand() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHexpand")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_GetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHexpand'
type MockBoxWidget_GetHexpand_Call struct {
	*mock.Call
}

// GetHexpand is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetHexpand() *MockBoxWidget_GetHexpand_Call {
	return &MockBoxWidget_GetHexpand_Call{Call: _e.mock.On("GetHexpand")}
}

func (_c *MockBoxWidget_GetHexpand_Call) Run(run func()) *MockBoxWidget_GetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetHexpand_Call) Return(_a0 bool) *MockBoxWidget_GetHexpand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetHexpand_Call) RunAndReturn(run func() bool) *MockBoxWidget_GetHexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GetHomogeneous provides a mock function with no fields
func (_m *MockBoxWidget) GetHomogeneous() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHomogeneous")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_GetHomogeneous_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHomogeneous'
type MockBoxWidget_GetHomogeneous_Call struct {
	*mock.Call
}

// GetHomogeneous is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetHomogeneous() *MockBoxWidget_GetHomogeneous_Call {
	return &MockBoxWidget_GetHomogeneous_Call{Call: _e.mock.On("GetHomogeneous")}
}

func (_c *MockBoxWidget_GetHomogeneous_Call) Run(run func()) *MockBoxWidget_GetHomogeneous_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetHomogeneous_Call) Return(_a0 bool) *MockBoxWidget_GetHomogeneous_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetHomogeneous_Call) RunAndReturn(run func() bool) *MockBoxWidget_GetHomogeneous_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrientation provides a mock function with no fields
func (_m *MockBoxWidget) GetOrientation() gtk.Orientation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrientation")
	}

	var r0 gtk.Orientation
	if rf, ok := ret.Get(0).(func() gtk.Orientation); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(gtk.Orientation)
	}

	return r0
}

// MockBoxWidget_GetOrientation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrientation'
type MockBoxWidget_GetOrientation_Call struct {
	*mock.Call
}

// GetOrientation is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetOrientation() *MockBoxWidget_GetOrientation_Call {
	return &MockBoxWidget_GetOrientation_Call{Call: _e.mock.On("GetOrientation")}
}

func (_c *MockBoxWidget_GetOrientation_Call) Run(run func()) *MockBoxWidget_GetOrientation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetOrientation_Call) Return(_a0 gtk.Orientation) *MockBoxWidget_GetOrientation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetOrientation_Call) RunAndReturn(run func() gtk.Orientation) *MockBoxWidget_GetOrientation_Call {
	_c.Call.Return(run)
	return _c
}

// GetParent provides a mock function with no fields
func (_m *MockBoxWidget) GetParent() layout.Widget {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParent")
	}

	var r0 layout.Widget
	if rf, ok := ret.Get(0).(func() layout.Widget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(layout.Widget)
		}
	}

	return r0
}

// MockBoxWidget_GetParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParent'
type MockBoxWidget_GetParent_Call struct {
	*mock.Call
}

// GetParent is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetParent() *MockBoxWidget_GetParent_Call {
	return &MockBoxWidget_GetParent_Call{Call: _e.mock.On("GetParent")}
}

func (_c *MockBoxWidget_GetParent_Call) Run(run func()) *MockBoxWidget_GetParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetParent_Call) Return(_a0 layout.Widget) *MockBoxWidget_GetParent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetParent_Call) RunAndReturn(run func() layout.Widget) *MockBoxWidget_GetParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpacing provides a mock function with no fields
func (_m *MockBoxWidget) GetSpacing() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpacing")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBoxWidget_GetSpacing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpacing'
type MockBoxWidget_GetSpacing_Call struct {
	*mock.Call
}

// GetSpacing is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetSpacing() *MockBoxWidget_GetSpacing_Call {
	return &MockBoxWidget_GetSpacing_Call{Call: _e.mock.On("GetSpacing")}
}

func (_c *MockBoxWidget_GetSpacing_Call) Run(run func()) *MockBoxWidget_GetSpacing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetSpacing_Call) Return(_a0 int) *MockBoxWidget_GetSpacing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetSpacing_Call) RunAndReturn(run func() int) *MockBoxWidget_GetSpacing_Call {
	_c.Call.Return(run)
	return _c
}

// GetVexpand provides a mock function with no fields
func (_m *MockBoxWidget) GetVexpand() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVexpand")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_GetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVexpand'
type MockBoxWidget_GetVexpand_Call struct {
	*mock.Call
}

// GetVexpand is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GetVexpand() *MockBoxWidget_GetVexpand_Call {
	return &MockBoxWidget_GetVexpand_Call{Call: _e.mock.On("GetVexpand")}
}

func (_c *MockBoxWidget_GetVexpand_Call) Run(run func()) *MockBoxWidget_GetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GetVexpand_Call) Return(_a0 bool) *MockBoxWidget_GetVexpand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GetVexpand_Call) RunAndReturn(run func() bool) *MockBoxWidget_GetVexpand_Call {
	_c.Call.Return(run)
	return _c
}

// GrabFocus provides a mock function with no fields
func (_m *MockBoxWidget) GrabFocus() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GrabFocus")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_GrabFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrabFocus'
type MockBoxWidget_GrabFocus_Call struct {
	*mock.Call
}

// GrabFocus is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GrabFocus() *MockBoxWidget_GrabFocus_Call {
	return &MockBoxWidget_GrabFocus_Call{Call: _e.mock.On("GrabFocus")}
}

func (_c *MockBoxWidget_GrabFocus_Call) Run(run func()) *MockBoxWidget_GrabFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GrabFocus_Call) Return(_a0 bool) *MockBoxWidget_GrabFocus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GrabFocus_Call) RunAndReturn(run func() bool) *MockBoxWidget_GrabFocus_Call {
	_c.Call.Return(run)
	return _c
}

// GtkWidget provides a mock function with no fields
func (_m *MockBoxWidget) GtkWidget() *gtk.Widget {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GtkWidget")
	}

	var r0 *gtk.Widget
	if rf, ok := ret.Get(0).(func() *gtk.Widget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gtk.Widget)
		}
	}

	return r0
}

// MockBoxWidget_GtkWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GtkWidget'
type MockBoxWidget_GtkWidget_Call struct {
	*mock.Call
}

// GtkWidget is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) GtkWidget() *MockBoxWidget_GtkWidget_Call {
	return &MockBoxWidget_GtkWidget_Call{Call: _e.mock.On("GtkWidget")}
}

func (_c *MockBoxWidget_GtkWidget_Call) Run(run func()) *MockBoxWidget_GtkWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_GtkWidget_Call) Return(_a0 *gtk.Widget) *MockBoxWidget_GtkWidget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_GtkWidget_Call) RunAndReturn(run func() *gtk.Widget) *MockBoxWidget_GtkWidget_Call {
	_c.Call.Return(run)
	return _c
}

// HasCssClass provides a mock function with given fields: cssClass
func (_m *MockBoxWidget) HasCssClass(cssClass string) bool {
	ret := _m.Called(cssClass)

	if len(ret) == 0 {
		panic("no return value specified for HasCssClass")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(cssClass)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_HasCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCssClass'
type MockBoxWidget_HasCssClass_Call struct {
	*mock.Call
}

// HasCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockBoxWidget_Expecter) HasCssClass(cssClass interface{}) *MockBoxWidget_HasCssClass_Call {
	return &MockBoxWidget_HasCssClass_Call{Call: _e.mock.On("HasCssClass", cssClass)}
}

func (_c *MockBoxWidget_HasCssClass_Call) Run(run func(cssClass string)) *MockBoxWidget_HasCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBoxWidget_HasCssClass_Call) Return(_a0 bool) *MockBoxWidget_HasCssClass_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_HasCssClass_Call) RunAndReturn(run func(string) bool) *MockBoxWidget_HasCssClass_Call {
	_c.Call.Return(run)
	return _c
}

// HasFocus provides a mock function with no fields
func (_m *MockBoxWidget) HasFocus() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasFocus")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_HasFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFocus'
type MockBoxWidget_HasFocus_Call struct {
	*mock.Call
}

// HasFocus is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) HasFocus() *MockBoxWidget_HasFocus_Call {
	return &MockBoxWidget_HasFocus_Call{Call: _e.mock.On("HasFocus")}
}

func (_c *MockBoxWidget_HasFocus_Call) Run(run func()) *MockBoxWidget_HasFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_HasFocus_Call) Return(_a0 bool) *MockBoxWidget_HasFocus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_HasFocus_Call) RunAndReturn(run func() bool) *MockBoxWidget_HasFocus_Call {
	_c.Call.Return(run)
	return _c
}

// Hide provides a mock function with no fields
func (_m *MockBoxWidget) Hide() {
	_m.Called()
}

// MockBoxWidget_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type MockBoxWidget_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) Hide() *MockBoxWidget_Hide_Call {
	return &MockBoxWidget_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *MockBoxWidget_Hide_Call) Run(run func()) *MockBoxWidget_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_Hide_Call) Return() *MockBoxWidget_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Hide_Call) RunAndReturn(run func()) *MockBoxWidget_Hide_Call {
	_c.Run(run)
	return _c
}

// InsertChildAfter provides a mock function with given fields: child, sibling
func (_m *MockBoxWidget) InsertChildAfter(child layout.Widget, sibling layout.Widget) {
	_m.Called(child, sibling)
}

// MockBoxWidget_InsertChildAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChildAfter'
type MockBoxWidget_InsertChildAfter_Call struct {
	*mock.Call
}

// InsertChildAfter is a helper method to define mock.On call
//   - child layout.Widget
//   - sibling layout.Widget
func (_e *MockBoxWidget_Expecter) InsertChildAfter(child interface{}, sibling interface{}) *MockBoxWidget_InsertChildAfter_Call {
	return &MockBoxWidget_InsertChildAfter_Call{Call: _e.mock.On("InsertChildAfter", child, sibling)}
}

func (_c *MockBoxWidget_InsertChildAfter_Call) Run(run func(child layout.Widget, sibling layout.Widget)) *MockBoxWidget_InsertChildAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget), args[1].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_InsertChildAfter_Call) Return() *MockBoxWidget_InsertChildAfter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_InsertChildAfter_Call) RunAndReturn(run func(layout.Widget, layout.Widget)) *MockBoxWidget_InsertChildAfter_Call {
	_c.Run(run)
	return _c
}

// IsVisible provides a mock function with no fields
func (_m *MockBoxWidget) IsVisible() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsVisible")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBoxWidget_IsVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVisible'
type MockBoxWidget_IsVisible_Call struct {
	*mock.Call
}

// IsVisible is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) IsVisible() *MockBoxWidget_IsVisible_Call {
	return &MockBoxWidget_IsVisible_Call{Call: _e.mock.On("IsVisible")}
}

func (_c *MockBoxWidget_IsVisible_Call) Run(run func()) *MockBoxWidget_IsVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_IsVisible_Call) Return(_a0 bool) *MockBoxWidget_IsVisible_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxWidget_IsVisible_Call) RunAndReturn(run func() bool) *MockBoxWidget_IsVisible_Call {
	_c.Call.Return(run)
	return _c
}

// Prepend provides a mock function with given fields: child
func (_m *MockBoxWidget) Prepend(child layout.Widget) {
	_m.Called(child)
}

// MockBoxWidget_Prepend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepend'
type MockBoxWidget_Prepend_Call struct {
	*mock.Call
}

// Prepend is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockBoxWidget_Expecter) Prepend(child interface{}) *MockBoxWidget_Prepend_Call {
	return &MockBoxWidget_Prepend_Call{Call: _e.mock.On("Prepend", child)}
}

func (_c *MockBoxWidget_Prepend_Call) Run(run func(child layout.Widget)) *MockBoxWidget_Prepend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_Prepend_Call) Return() *MockBoxWidget_Prepend_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Prepend_Call) RunAndReturn(run func(layout.Widget)) *MockBoxWidget_Prepend_Call {
	_c.Run(run)
	return _c
}

// Remove provides a mock function with given fields: child
func (_m *MockBoxWidget) Remove(child layout.Widget) {
	_m.Called(child)
}

// MockBoxWidget_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockBoxWidget_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - child layout.Widget
func (_e *MockBoxWidget_Expecter) Remove(child interface{}) *MockBoxWidget_Remove_Call {
	return &MockBoxWidget_Remove_Call{Call: _e.mock.On("Remove", child)}
}

func (_c *MockBoxWidget_Remove_Call) Run(run func(child layout.Widget)) *MockBoxWidget_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_Remove_Call) Return() *MockBoxWidget_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Remove_Call) RunAndReturn(run func(layout.Widget)) *MockBoxWidget_Remove_Call {
	_c.Run(run)
	return _c
}

// RemoveCssClass provides a mock function with given fields: cssClass
func (_m *MockBoxWidget) RemoveCssClass(cssClass string) {
	_m.Called(cssClass)
}

// MockBoxWidget_RemoveCssClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCssClass'
type MockBoxWidget_RemoveCssClass_Call struct {
	*mock.Call
}

// RemoveCssClass is a helper method to define mock.On call
//   - cssClass string
func (_e *MockBoxWidget_Expecter) RemoveCssClass(cssClass interface{}) *MockBoxWidget_RemoveCssClass_Call {
	return &MockBoxWidget_RemoveCssClass_Call{Call: _e.mock.On("RemoveCssClass", cssClass)}
}

func (_c *MockBoxWidget_RemoveCssClass_Call) Run(run func(cssClass string)) *MockBoxWidget_RemoveCssClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBoxWidget_RemoveCssClass_Call) Return() *MockBoxWidget_RemoveCssClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_RemoveCssClass_Call) RunAndReturn(run func(string)) *MockBoxWidget_RemoveCssClass_Call {
	_c.Run(run)
	return _c
}

// ReorderChildAfter provides a mock function with given fields: child, sibling
func (_m *MockBoxWidget) ReorderChildAfter(child layout.Widget, sibling layout.Widget) {
	_m.Called(child, sibling)
}

// MockBoxWidget_ReorderChildAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReorderChildAfter'
type MockBoxWidget_ReorderChildAfter_Call struct {
	*mock.Call
}

// ReorderChildAfter is a helper method to define mock.On call
//   - child layout.Widget
//   - sibling layout.Widget
func (_e *MockBoxWidget_Expecter) ReorderChildAfter(child interface{}, sibling interface{}) *MockBoxWidget_ReorderChildAfter_Call {
	return &MockBoxWidget_ReorderChildAfter_Call{Call: _e.mock.On("ReorderChildAfter", child, sibling)}
}

func (_c *MockBoxWidget_ReorderChildAfter_Call) Run(run func(child layout.Widget, sibling layout.Widget)) *MockBoxWidget_ReorderChildAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(layout.Widget), args[1].(layout.Widget))
	})
	return _c
}

func (_c *MockBoxWidget_ReorderChildAfter_Call) Return() *MockBoxWidget_ReorderChildAfter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_ReorderChildAfter_Call) RunAndReturn(run func(layout.Widget, layout.Widget)) *MockBoxWidget_ReorderChildAfter_Call {
	_c.Run(run)
	return _c
}

// SetCanFocus provides a mock function with given fields: canFocus
func (_m *MockBoxWidget) SetCanFocus(canFocus bool) {
	_m.Called(canFocus)
}

// MockBoxWidget_SetCanFocus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanFocus'
type MockBoxWidget_SetCanFocus_Call struct {
	*mock.Call
}

// SetCanFocus is a helper method to define mock.On call
//   - canFocus bool
func (_e *MockBoxWidget_Expecter) SetCanFocus(canFocus interface{}) *MockBoxWidget_SetCanFocus_Call {
	return &MockBoxWidget_SetCanFocus_Call{Call: _e.mock.On("SetCanFocus", canFocus)}
}

func (_c *MockBoxWidget_SetCanFocus_Call) Run(run func(canFocus bool)) *MockBoxWidget_SetCanFocus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetCanFocus_Call) Return() *MockBoxWidget_SetCanFocus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetCanFocus_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetCanFocus_Call {
	_c.Run(run)
	return _c
}

// SetCanTarget provides a mock function with given fields: canTarget
func (_m *MockBoxWidget) SetCanTarget(canTarget bool) {
	_m.Called(canTarget)
}

// MockBoxWidget_SetCanTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCanTarget'
type MockBoxWidget_SetCanTarget_Call struct {
	*mock.Call
}

// SetCanTarget is a helper method to define mock.On call
//   - canTarget bool
func (_e *MockBoxWidget_Expecter) SetCanTarget(canTarget interface{}) *MockBoxWidget_SetCanTarget_Call {
	return &MockBoxWidget_SetCanTarget_Call{Call: _e.mock.On("SetCanTarget", canTarget)}
}

func (_c *MockBoxWidget_SetCanTarget_Call) Run(run func(canTarget bool)) *MockBoxWidget_SetCanTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetCanTarget_Call) Return() *MockBoxWidget_SetCanTarget_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetCanTarget_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetCanTarget_Call {
	_c.Run(run)
	return _c
}

// SetFocusOnClick provides a mock function with given fields: focusOnClick
func (_m *MockBoxWidget) SetFocusOnClick(focusOnClick bool) {
	_m.Called(focusOnClick)
}

// MockBoxWidget_SetFocusOnClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFocusOnClick'
type MockBoxWidget_SetFocusOnClick_Call struct {
	*mock.Call
}

// SetFocusOnClick is a helper method to define mock.On call
//   - focusOnClick bool
func (_e *MockBoxWidget_Expecter) SetFocusOnClick(focusOnClick interface{}) *MockBoxWidget_SetFocusOnClick_Call {
	return &MockBoxWidget_SetFocusOnClick_Call{Call: _e.mock.On("SetFocusOnClick", focusOnClick)}
}

func (_c *MockBoxWidget_SetFocusOnClick_Call) Run(run func(focusOnClick bool)) *MockBoxWidget_SetFocusOnClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetFocusOnClick_Call) Return() *MockBoxWidget_SetFocusOnClick_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetFocusOnClick_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetFocusOnClick_Call {
	_c.Run(run)
	return _c
}

// SetHalign provides a mock function with given fields: align
func (_m *MockBoxWidget) SetHalign(align gtk.Align) {
	_m.Called(align)
}

// MockBoxWidget_SetHalign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHalign'
type MockBoxWidget_SetHalign_Call struct {
	*mock.Call
}

// SetHalign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockBoxWidget_Expecter) SetHalign(align interface{}) *MockBoxWidget_SetHalign_Call {
	return &MockBoxWidget_SetHalign_Call{Call: _e.mock.On("SetHalign", align)}
}

func (_c *MockBoxWidget_SetHalign_Call) Run(run func(align gtk.Align)) *MockBoxWidget_SetHalign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gtk.Align))
	})
	return _c
}

func (_c *MockBoxWidget_SetHalign_Call) Return() *MockBoxWidget_SetHalign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetHalign_Call) RunAndReturn(run func(gtk.Align)) *MockBoxWidget_SetHalign_Call {
	_c.Run(run)
	return _c
}

// SetHexpand provides a mock function with given fields: expand
func (_m *MockBoxWidget) SetHexpand(expand bool) {
	_m.Called(expand)
}

// MockBoxWidget_SetHexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHexpand'
type MockBoxWidget_SetHexpand_Call struct {
	*mock.Call
}

// SetHexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockBoxWidget_Expecter) SetHexpand(expand interface{}) *MockBoxWidget_SetHexpand_Call {
	return &MockBoxWidget_SetHexpand_Call{Call: _e.mock.On("SetHexpand", expand)}
}

func (_c *MockBoxWidget_SetHexpand_Call) Run(run func(expand bool)) *MockBoxWidget_SetHexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetHexpand_Call) Return() *MockBoxWidget_SetHexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetHexpand_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetHexpand_Call {
	_c.Run(run)
	return _c
}

// SetHomogeneous provides a mock function with given fields: homogeneous
func (_m *MockBoxWidget) SetHomogeneous(homogeneous bool) {
	_m.Called(homogeneous)
}

// MockBoxWidget_SetHomogeneous_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHomogeneous'
type MockBoxWidget_SetHomogeneous_Call struct {
	*mock.Call
}

// SetHomogeneous is a helper method to define mock.On call
//   - homogeneous bool
func (_e *MockBoxWidget_Expecter) SetHomogeneous(homogeneous interface{}) *MockBoxWidget_SetHomogeneous_Call {
	return &MockBoxWidget_SetHomogeneous_Call{Call: _e.mock.On("SetHomogeneous", homogeneous)}
}

func (_c *MockBoxWidget_SetHomogeneous_Call) Run(run func(homogeneous bool)) *MockBoxWidget_SetHomogeneous_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetHomogeneous_Call) Return() *MockBoxWidget_SetHomogeneous_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetHomogeneous_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetHomogeneous_Call {
	_c.Run(run)
	return _c
}

// SetOrientation provides a mock function with given fields: orientation
func (_m *MockBoxWidget) SetOrientation(orientation gtk.Orientation) {
	_m.Called(orientation)
}

// MockBoxWidget_SetOrientation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrientation'
type MockBoxWidget_SetOrientation_Call struct {
	*mock.Call
}

// SetOrientation is a helper method to define mock.On call
//   - orientation gtk.Orientation
func (_e *MockBoxWidget_Expecter) SetOrientation(orientation interface{}) *MockBoxWidget_SetOrientation_Call {
	return &MockBoxWidget_SetOrientation_Call{Call: _e.mock.On("SetOrientation", orientation)}
}

func (_c *MockBoxWidget_SetOrientation_Call) Run(run func(orientation gtk.Orientation)) *MockBoxWidget_SetOrientation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gtk.Orientation))
	})
	return _c
}

func (_c *MockBoxWidget_SetOrientation_Call) Return() *MockBoxWidget_SetOrientation_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetOrientation_Call) RunAndReturn(run func(gtk.Orientation)) *MockBoxWidget_SetOrientation_Call {
	_c.Run(run)
	return _c
}

// SetSizeRequest provides a mock function with given fields: width, height
func (_m *MockBoxWidget) SetSizeRequest(width int, height int) {
	_m.Called(width, height)
}

// MockBoxWidget_SetSizeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSizeRequest'
type MockBoxWidget_SetSizeRequest_Call struct {
	*mock.Call
}

// SetSizeRequest is a helper method to define mock.On call
//   - width int
//   - height int
func (_e *MockBoxWidget_Expecter) SetSizeRequest(width interface{}, height interface{}) *MockBoxWidget_SetSizeRequest_Call {
	return &MockBoxWidget_SetSizeRequest_Call{Call: _e.mock.On("SetSizeRequest", width, height)}
}

func (_c *MockBoxWidget_SetSizeRequest_Call) Run(run func(width int, height int)) *MockBoxWidget_SetSizeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBoxWidget_SetSizeRequest_Call) Return() *MockBoxWidget_SetSizeRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetSizeRequest_Call) RunAndReturn(run func(int, int)) *MockBoxWidget_SetSizeRequest_Call {
	_c.Run(run)
	return _c
}

// SetSpacing provides a mock function with given fields: spacing
func (_m *MockBoxWidget) SetSpacing(spacing int) {
	_m.Called(spacing)
}

// MockBoxWidget_SetSpacing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSpacing'
type MockBoxWidget_SetSpacing_Call struct {
	*mock.Call
}

// SetSpacing is a helper method to define mock.On call
//   - spacing int
func (_e *MockBoxWidget_Expecter) SetSpacing(spacing interface{}) *MockBoxWidget_SetSpacing_Call {
	return &MockBoxWidget_SetSpacing_Call{Call: _e.mock.On("SetSpacing", spacing)}
}

func (_c *MockBoxWidget_SetSpacing_Call) Run(run func(spacing int)) *MockBoxWidget_SetSpacing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBoxWidget_SetSpacing_Call) Return() *MockBoxWidget_SetSpacing_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetSpacing_Call) RunAndReturn(run func(int)) *MockBoxWidget_SetSpacing_Call {
	_c.Run(run)
	return _c
}

// SetValign provides a mock function with given fields: align
func (_m *MockBoxWidget) SetValign(align gtk.Align) {
	_m.Called(align)
}

// MockBoxWidget_SetValign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValign'
type MockBoxWidget_SetValign_Call struct {
	*mock.Call
}

// SetValign is a helper method to define mock.On call
//   - align gtk.Align
func (_e *MockBoxWidget_Expecter) SetValign(align interface{}) *MockBoxWidget_SetValign_Call {
	return &MockBoxWidget_SetValign_Call{Call: _e.mock.On("SetValign", align)}
}

func (_c *MockBoxWidget_SetValign_Call) Run(run func(align gtk.Align)) *MockBoxWidget_SetValign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gtk.Align))
	})
	return _c
}

func (_c *MockBoxWidget_SetValign_Call) Return() *MockBoxWidget_SetValign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetValign_Call) RunAndReturn(run func(gtk.Align)) *MockBoxWidget_SetValign_Call {
	_c.Run(run)
	return _c
}

// SetVexpand provides a mock function with given fields: expand
func (_m *MockBoxWidget) SetVexpand(expand bool) {
	_m.Called(expand)
}

// MockBoxWidget_SetVexpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVexpand'
type MockBoxWidget_SetVexpand_Call struct {
	*mock.Call
}

// SetVexpand is a helper method to define mock.On call
//   - expand bool
func (_e *MockBoxWidget_Expecter) SetVexpand(expand interface{}) *MockBoxWidget_SetVexpand_Call {
	return &MockBoxWidget_SetVexpand_Call{Call: _e.mock.On("SetVexpand", expand)}
}

func (_c *MockBoxWidget_SetVexpand_Call) Run(run func(expand bool)) *MockBoxWidget_SetVexpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetVexpand_Call) Return() *MockBoxWidget_SetVexpand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetVexpand_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetVexpand_Call {
	_c.Run(run)
	return _c
}

// SetVisible provides a mock function with given fields: visible
func (_m *MockBoxWidget) SetVisible(visible bool) {
	_m.Called(visible)
}

// MockBoxWidget_SetVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVisible'
type MockBoxWidget_SetVisible_Call struct {
	*mock.Call
}

// SetVisible is a helper method to define mock.On call
//   - visible bool
func (_e *MockBoxWidget_Expecter) SetVisible(visible interface{}) *MockBoxWidget_SetVisible_Call {
	return &MockBoxWidget_SetVisible_Call{Call: _e.mock.On("SetVisible", visible)}
}

func (_c *MockBoxWidget_SetVisible_Call) Run(run func(visible bool)) *MockBoxWidget_SetVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockBoxWidget_SetVisible_Call) Return() *MockBoxWidget_SetVisible_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_SetVisible_Call) RunAndReturn(run func(bool)) *MockBoxWidget_SetVisible_Call {
	_c.Run(run)
	return _c
}

// Show provides a mock function with no fields
func (_m *MockBoxWidget) Show() {
	_m.Called()
}

// MockBoxWidget_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockBoxWidget_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) Show() *MockBoxWidget_Show_Call {
	return &MockBoxWidget_Show_Call{Call: _e.mock.On("Show")}
}

func (_c *MockBoxWidget_Show_Call) Run(run func()) *MockBoxWidget_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_Show_Call) Return() *MockBoxWidget_Show_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Show_Call) RunAndReturn(run func()) *MockBoxWidget_Show_Call {
	_c.Run(run)
	return _c
}

// Unparent provides a mock function with no fields
func (_m *MockBoxWidget) Unparent() {
	_m.Called()
}

// MockBoxWidget_Unparent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unparent'
type MockBoxWidget_Unparent_Call struct {
	*mock.Call
}

// Unparent is a helper method to define mock.On call
func (_e *MockBoxWidget_Expecter) Unparent() *MockBoxWidget_Unparent_Call {
	return &MockBoxWidget_Unparent_Call{Call: _e.mock.On("Unparent")}
}

func (_c *MockBoxWidget_Unparent_Call) Run(run func()) *MockBoxWidget_Unparent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBoxWidget_Unparent_Call) Return() *MockBoxWidget_Unparent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoxWidget_Unparent_Call) RunAndReturn(run func()) *MockBoxWidget_Unparent_Call {
	_c.Run(run)
	return _c
}

// NewMockBoxWidget creates a new instance of MockBoxWidget. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoxWidget(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoxWidget {
	mock := &MockBoxWidget{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
