// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/dumber/internal/infrastructure/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigChangeManager creates a new instance of MockConfigChangeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigChangeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigChangeManager {
	mock := &MockConfigChangeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigChangeManager is an autogenerated mock type for the configChangeManager type
type MockConfigChangeManager struct {
	mock.Mock
}

type MockConfigChangeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigChangeManager) EXPECT() *MockConfigChangeManager_Expecter {
	return &MockConfigChangeManager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockConfigChangeManager
func (_mock *MockConfigChangeManager) Get() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// MockConfigChangeManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfigChangeManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockConfigChangeManager_Expecter) Get() *MockConfigChangeManager_Get_Call {
	return &MockConfigChangeManager_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockConfigChangeManager_Get_Call) Run(run func()) *MockConfigChangeManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigChangeManager_Get_Call) Return(config1 *config.Config) *MockConfigChangeManager_Get_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockConfigChangeManager_Get_Call) RunAndReturn(run func() *config.Config) *MockConfigChangeManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// OnConfigChange provides a mock function for the type MockConfigChangeManager
func (_mock *MockConfigChangeManager) OnConfigChange(fn func(*config.Config)) {
	_mock.Called(fn)
	return
}

// MockConfigChangeManager_OnConfigChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigChange'
type MockConfigChangeManager_OnConfigChange_Call struct {
	*mock.Call
}

// OnConfigChange is a helper method to define mock.On call
//   - fn func(*config.Config)
func (_e *MockConfigChangeManager_Expecter) OnConfigChange(fn any) *MockConfigChangeManager_OnConfigChange_Call {
	return &MockConfigChangeManager_OnConfigChange_Call{Call: _e.mock.On("OnConfigChange", fn)}
}

func (_c *MockConfigChangeManager_OnConfigChange_Call) Run(run func(fn func(*config.Config))) *MockConfigChangeManager_OnConfigChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*config.Config)
		if args[0] != nil {
			arg0 = args[0].(func(*config.Config))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigChangeManager_OnConfigChange_Call) Return() *MockConfigChangeManager_OnConfigChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigChangeManager_OnConfigChange_Call) RunAndReturn(run func(fn func(*config.Config))) *MockConfigChangeManager_OnConfigChange_Call {
	_c.Run(run)
	return _c
}

// Watch provides a mock function for the type MockConfigChangeManager
func (_mock *MockConfigChangeManager) Watch() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigChangeManager_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockConfigChangeManager_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
func (_e *MockConfigChangeManager_Expecter) Watch() *MockConfigChangeManager_Watch_Call {
	return &MockConfigChangeManager_Watch_Call{Call: _e.mock.On("Watch")}
}

func (_c *MockConfigChangeManager_Watch_Call) Run(run func()) *MockConfigChangeManager_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigChangeManager_Watch_Call) Return(err error) *MockConfigChangeManager_Watch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigChangeManager_Watch_Call) RunAndReturn(run func() error) *MockConfigChangeManager_Watch_Call {
	_c.Call.Return(run)
	return _c
}
