// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
	"database/sql"
)

const DeleteAllHistory = `-- name: DeleteAllHistory :exec
DELETE FROM history
`

func (q *Queries) DeleteAllHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllHistory)
	return err
}

const DeleteHistoryByID = `-- name: DeleteHistoryByID :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistoryByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteHistoryByID, id)
	return err
}

const DeleteHistoryOlderThan = `-- name: DeleteHistoryOlderThan :exec
DELETE FROM history WHERE last_visited < ?
`

func (q *Queries) DeleteHistoryOlderThan(ctx context.Context, lastVisited sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, DeleteHistoryOlderThan, lastVisited)
	return err
}

const GetHistoryByURL = `-- name: GetHistoryByURL :one
SELECT id, url, title, favicon_url, visit_count, last_visited, created_at FROM history WHERE url = ? LIMIT 1
`

func (q *Queries) GetHistoryByURL(ctx context.Context, url string) (History, error) {
	row := q.db.QueryRowContext(ctx, GetHistoryByURL, url)
	var i History
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FaviconUrl,
		&i.VisitCount,
		&i.LastVisited,
		&i.CreatedAt,
	)
	return i, err
}

const GetRecentHistory = `-- name: GetRecentHistory :many
SELECT id, url, title, favicon_url, visit_count, last_visited, created_at FROM history ORDER BY last_visited DESC LIMIT ? OFFSET ?
`

type GetRecentHistoryParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetRecentHistory(ctx context.Context, arg GetRecentHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, GetRecentHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FaviconUrl,
			&i.VisitCount,
			&i.LastVisited,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IncrementVisitCount = `-- name: IncrementVisitCount :exec
UPDATE history
SET visit_count = visit_count + 1, last_visited = CURRENT_TIMESTAMP
WHERE url = ?
`

func (q *Queries) IncrementVisitCount(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, IncrementVisitCount, url)
	return err
}

const SearchHistory = `-- name: SearchHistory :many
SELECT id, url, title, favicon_url, visit_count, last_visited, created_at FROM history
WHERE url LIKE '%' || ? || '%' OR title LIKE '%' || ? || '%'
ORDER BY visit_count DESC, last_visited DESC
LIMIT ?
`

type SearchHistoryParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchHistory(ctx context.Context, arg SearchHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, SearchHistory, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FaviconUrl,
			&i.VisitCount,
			&i.LastVisited,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertHistory = `-- name: UpsertHistory :exec
INSERT INTO history (url, title, favicon_url)
VALUES (?, ?, ?)
ON CONFLICT(url)
DO UPDATE SET
    visit_count = visit_count + 1,
    last_visited = CURRENT_TIMESTAMP,
    title = COALESCE(EXCLUDED.title, history.title),
    favicon_url = COALESCE(EXCLUDED.favicon_url, history.favicon_url)
`

type UpsertHistoryParams struct {
	Url        string         `json:"url"`
	Title      sql.NullString `json:"title"`
	FaviconUrl sql.NullString `json:"favicon_url"`
}

func (q *Queries) UpsertHistory(ctx context.Context, arg UpsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, UpsertHistory, arg.Url, arg.Title, arg.FaviconUrl)
	return err
}
