// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
)

const AssignTagToFavorite = `-- name: AssignTagToFavorite :exec
INSERT OR IGNORE INTO favorite_tag_assignments (favorite_id, tag_id) VALUES (?, ?)
`

type AssignTagToFavoriteParams struct {
	FavoriteID int64 `json:"favorite_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) AssignTagToFavorite(ctx context.Context, arg AssignTagToFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, AssignTagToFavorite, arg.FavoriteID, arg.TagID)
	return err
}

const CreateTag = `-- name: CreateTag :one
INSERT INTO favorite_tags (name, color) VALUES (?, ?) RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (FavoriteTag, error) {
	row := q.db.QueryRowContext(ctx, CreateTag, arg.Name, arg.Color)
	var i FavoriteTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteTag = `-- name: DeleteTag :exec
DELETE FROM favorite_tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTag, id)
	return err
}

const GetAllTags = `-- name: GetAllTags :many
SELECT id, name, color, created_at FROM favorite_tags ORDER BY name ASC
`

func (q *Queries) GetAllTags(ctx context.Context) ([]FavoriteTag, error) {
	rows, err := q.db.QueryContext(ctx, GetAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FavoriteTag{}
	for rows.Next() {
		var i FavoriteTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTagByID = `-- name: GetTagByID :one
SELECT id, name, color, created_at FROM favorite_tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (FavoriteTag, error) {
	row := q.db.QueryRowContext(ctx, GetTagByID, id)
	var i FavoriteTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const GetTagByName = `-- name: GetTagByName :one
SELECT id, name, color, created_at FROM favorite_tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (FavoriteTag, error) {
	row := q.db.QueryRowContext(ctx, GetTagByName, name)
	var i FavoriteTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const GetTagsForFavorite = `-- name: GetTagsForFavorite :many
SELECT t.id, t.name, t.color, t.created_at FROM favorite_tags t
INNER JOIN favorite_tag_assignments fta ON t.id = fta.tag_id
WHERE fta.favorite_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForFavorite(ctx context.Context, favoriteID int64) ([]FavoriteTag, error) {
	rows, err := q.db.QueryContext(ctx, GetTagsForFavorite, favoriteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FavoriteTag{}
	for rows.Next() {
		var i FavoriteTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveTagFromFavorite = `-- name: RemoveTagFromFavorite :exec
DELETE FROM favorite_tag_assignments WHERE favorite_id = ? AND tag_id = ?
`

type RemoveTagFromFavoriteParams struct {
	FavoriteID int64 `json:"favorite_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromFavorite(ctx context.Context, arg RemoveTagFromFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, RemoveTagFromFavorite, arg.FavoriteID, arg.TagID)
	return err
}

const UpdateTag = `-- name: UpdateTag :exec
UPDATE favorite_tags SET name = ?, color = ? WHERE id = ?
`

type UpdateTagParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTag, arg.Name, arg.Color, arg.ID)
	return err
}
