// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whitelist.sql

package sqlc

import (
	"context"
)

const AddToWhitelist = `-- name: AddToWhitelist :exec
INSERT OR IGNORE INTO content_whitelist (domain, created_at) VALUES (?, CURRENT_TIMESTAMP)
`

func (q *Queries) AddToWhitelist(ctx context.Context, domain string) error {
	_, err := q.db.ExecContext(ctx, AddToWhitelist, domain)
	return err
}

const GetAllWhitelistedDomains = `-- name: GetAllWhitelistedDomains :many
SELECT domain FROM content_whitelist ORDER BY domain
`

func (q *Queries) GetAllWhitelistedDomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, GetAllWhitelistedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IsWhitelisted = `-- name: IsWhitelisted :one
SELECT COUNT(*) FROM content_whitelist WHERE domain = ? LIMIT 1
`

func (q *Queries) IsWhitelisted(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRowContext(ctx, IsWhitelisted, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const RemoveFromWhitelist = `-- name: RemoveFromWhitelist :exec
DELETE FROM content_whitelist WHERE domain = ?
`

func (q *Queries) RemoveFromWhitelist(ctx context.Context, domain string) error {
	_, err := q.db.ExecContext(ctx, RemoveFromWhitelist, domain)
	return err
}
