// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/bnema/dumber/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockFolderRepository is an autogenerated mock type for the FolderRepository type
type MockFolderRepository struct {
	mock.Mock
}

type MockFolderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFolderRepository) EXPECT() *MockFolderRepository_Expecter {
	return &MockFolderRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockFolderRepository) Delete(ctx context.Context, id entity.FolderID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.FolderID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFolderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFolderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.FolderID
func (_e *MockFolderRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockFolderRepository_Delete_Call {
	return &MockFolderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFolderRepository_Delete_Call) Run(run func(ctx context.Context, id entity.FolderID)) *MockFolderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.FolderID))
	})
	return _c
}

func (_c *MockFolderRepository_Delete_Call) Return(_a0 error) *MockFolderRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFolderRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.FolderID) error) *MockFolderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockFolderRepository) FindByID(ctx context.Context, id entity.FolderID) (*entity.Folder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.FolderID) (*entity.Folder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.FolderID) *entity.Folder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.FolderID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFolderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockFolderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.FolderID
func (_e *MockFolderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockFolderRepository_FindByID_Call {
	return &MockFolderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockFolderRepository_FindByID_Call) Run(run func(ctx context.Context, id entity.FolderID)) *MockFolderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.FolderID))
	})
	return _c
}

func (_c *MockFolderRepository_FindByID_Call) Return(_a0 *entity.Folder, _a1 error) *MockFolderRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFolderRepository_FindByID_Call) RunAndReturn(run func(context.Context, entity.FolderID) (*entity.Folder, error)) *MockFolderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockFolderRepository) GetAll(ctx context.Context) ([]*entity.Folder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Folder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Folder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFolderRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockFolderRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFolderRepository_Expecter) GetAll(ctx interface{}) *MockFolderRepository_GetAll_Call {
	return &MockFolderRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockFolderRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockFolderRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFolderRepository_GetAll_Call) Return(_a0 []*entity.Folder, _a1 error) *MockFolderRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFolderRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*entity.Folder, error)) *MockFolderRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function with given fields: ctx, parentID
func (_m *MockFolderRepository) GetChildren(ctx context.Context, parentID *entity.FolderID) ([]*entity.Folder, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []*entity.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FolderID) ([]*entity.Folder, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FolderID) []*entity.Folder); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.FolderID) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFolderRepository_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockFolderRepository_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *entity.FolderID
func (_e *MockFolderRepository_Expecter) GetChildren(ctx interface{}, parentID interface{}) *MockFolderRepository_GetChildren_Call {
	return &MockFolderRepository_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, parentID)}
}

func (_c *MockFolderRepository_GetChildren_Call) Run(run func(ctx context.Context, parentID *entity.FolderID)) *MockFolderRepository_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.FolderID))
	})
	return _c
}

func (_c *MockFolderRepository_GetChildren_Call) Return(_a0 []*entity.Folder, _a1 error) *MockFolderRepository_GetChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFolderRepository_GetChildren_Call) RunAndReturn(run func(context.Context, *entity.FolderID) ([]*entity.Folder, error)) *MockFolderRepository_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, folder
func (_m *MockFolderRepository) Save(ctx context.Context, folder *entity.Folder) error {
	ret := _m.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Folder) error); ok {
		r0 = rf(ctx, folder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFolderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockFolderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - folder *entity.Folder
func (_e *MockFolderRepository_Expecter) Save(ctx interface{}, folder interface{}) *MockFolderRepository_Save_Call {
	return &MockFolderRepository_Save_Call{Call: _e.mock.On("Save", ctx, folder)}
}

func (_c *MockFolderRepository_Save_Call) Run(run func(ctx context.Context, folder *entity.Folder)) *MockFolderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Folder))
	})
	return _c
}

func (_c *MockFolderRepository_Save_Call) Return(_a0 error) *MockFolderRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFolderRepository_Save_Call) RunAndReturn(run func(context.Context, *entity.Folder) error) *MockFolderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosition provides a mock function with given fields: ctx, id, position
func (_m *MockFolderRepository) UpdatePosition(ctx context.Context, id entity.FolderID, position int) error {
	ret := _m.Called(ctx, id, position)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.FolderID, int) error); ok {
		r0 = rf(ctx, id, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFolderRepository_UpdatePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosition'
type MockFolderRepository_UpdatePosition_Call struct {
	*mock.Call
}

// UpdatePosition is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.FolderID
//   - position int
func (_e *MockFolderRepository_Expecter) UpdatePosition(ctx interface{}, id interface{}, position interface{}) *MockFolderRepository_UpdatePosition_Call {
	return &MockFolderRepository_UpdatePosition_Call{Call: _e.mock.On("UpdatePosition", ctx, id, position)}
}

func (_c *MockFolderRepository_UpdatePosition_Call) Run(run func(ctx context.Context, id entity.FolderID, position int)) *MockFolderRepository_UpdatePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.FolderID), args[2].(int))
	})
	return _c
}

func (_c *MockFolderRepository_UpdatePosition_Call) Return(_a0 error) *MockFolderRepository_UpdatePosition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFolderRepository_UpdatePosition_Call) RunAndReturn(run func(context.Context, entity.FolderID, int) error) *MockFolderRepository_UpdatePosition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFolderRepository creates a new instance of MockFolderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFolderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFolderRepository {
	mock := &MockFolderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
