// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorite_folders.sql

package db

import (
	"context"
	"database/sql"
)

const CreateFolder = `-- name: CreateFolder :one
INSERT INTO favorite_folders (name, icon, position)
VALUES (
    ?,
    ?,
    COALESCE((SELECT MAX(position) + 1 FROM favorite_folders), 0)
)
RETURNING id, name, icon, position, created_at
`

// Insert a new folder with auto-incremented position
func (q *Queries) CreateFolder(ctx context.Context, name string, icon sql.NullString) (FavoriteFolder, error) {
	row := q.db.QueryRowContext(ctx, CreateFolder, name, icon)
	var i FavoriteFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteFolder = `-- name: DeleteFolder :exec
DELETE FROM favorite_folders
WHERE id = ?
`

// Delete a folder by ID (favorites will have folder_id set to NULL)
func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteFolder, id)
	return err
}

const GetAllFolders = `-- name: GetAllFolders :many

SELECT id, name, icon, position, created_at
FROM favorite_folders
ORDER BY position ASC
`

// Favorite folders CRUD operations
// Get all folders ordered by position
func (q *Queries) GetAllFolders(ctx context.Context) ([]FavoriteFolder, error) {
	rows, err := q.db.QueryContext(ctx, GetAllFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FavoriteFolder{}
	for rows.Next() {
		var i FavoriteFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFavoritesInFolder = `-- name: GetFavoritesInFolder :many
SELECT f.id, f.url, f.title, f.favicon_url, f.position, f.created_at, f.updated_at, f.folder_id, f.shortcut_key
FROM favorites f
WHERE f.folder_id = ?
ORDER BY f.position ASC
`

// Get all favorites in a specific folder
func (q *Queries) GetFavoritesInFolder(ctx context.Context, folderID sql.NullInt64) ([]Favorite, error) {
	rows, err := q.db.QueryContext(ctx, GetFavoritesInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Favorite{}
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FaviconUrl,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FolderID,
			&i.ShortcutKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFavoritesWithoutFolder = `-- name: GetFavoritesWithoutFolder :many
SELECT id, url, title, favicon_url, position, created_at, updated_at, folder_id, shortcut_key
FROM favorites
WHERE folder_id IS NULL
ORDER BY position ASC
`

// Get all favorites not in any folder
func (q *Queries) GetFavoritesWithoutFolder(ctx context.Context) ([]Favorite, error) {
	rows, err := q.db.QueryContext(ctx, GetFavoritesWithoutFolder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Favorite{}
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FaviconUrl,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FolderID,
			&i.ShortcutKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFolderByID = `-- name: GetFolderByID :one
SELECT id, name, icon, position, created_at
FROM favorite_folders
WHERE id = ?
LIMIT 1
`

// Get a specific folder by ID
func (q *Queries) GetFolderByID(ctx context.Context, id int64) (FavoriteFolder, error) {
	row := q.db.QueryRowContext(ctx, GetFolderByID, id)
	var i FavoriteFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const GetFolderCount = `-- name: GetFolderCount :one
SELECT COUNT(*) as count
FROM favorite_folders
`

// Get total count of folders
func (q *Queries) GetFolderCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetFolderCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const UpdateFolder = `-- name: UpdateFolder :exec
UPDATE favorite_folders
SET
    name = ?,
    icon = ?
WHERE id = ?
`

// Update folder name and icon
func (q *Queries) UpdateFolder(ctx context.Context, name string, icon sql.NullString, iD int64) error {
	_, err := q.db.ExecContext(ctx, UpdateFolder, name, icon, iD)
	return err
}

const UpdateFolderPosition = `-- name: UpdateFolderPosition :exec
UPDATE favorite_folders
SET position = ?
WHERE id = ?
`

// Update folder position
func (q *Queries) UpdateFolderPosition(ctx context.Context, position int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, UpdateFolderPosition, position, iD)
	return err
}
