// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type CertificateValidation struct {
	ID              int64        `json:"id"`
	Hostname        string       `json:"hostname"`
	CertificateHash string       `json:"certificate_hash"`
	UserDecision    string       `json:"user_decision"`
	CreatedAt       sql.NullTime `json:"created_at"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
}

type Favorite struct {
	ID         int64          `json:"id"`
	Url        string         `json:"url"`
	Title      sql.NullString `json:"title"`
	FaviconUrl sql.NullString `json:"favicon_url"`
	Position   int64          `json:"position"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type FuzzyCacheMetadatum struct {
	ID           int64  `json:"id"`
	Version      int64  `json:"version"`
	EntryCount   int64  `json:"entry_count"`
	LastModified int64  `json:"last_modified"`
	EntriesHash  string `json:"entries_hash"`
}

type FuzzyCacheStructure struct {
	ID           int64  `json:"id"`
	TrigramIndex []byte `json:"trigram_index"`
	PrefixTrie   []byte `json:"prefix_trie"`
	SortedIndex  []byte `json:"sorted_index"`
}

type History struct {
	ID          int64          `json:"id"`
	Url         string         `json:"url"`
	Title       sql.NullString `json:"title"`
	VisitCount  sql.NullInt64  `json:"visit_count"`
	LastVisited sql.NullTime   `json:"last_visited"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	FaviconUrl  sql.NullString `json:"favicon_url"`
}

type ZoomLevel struct {
	Domain     string       `json:"domain"`
	ZoomFactor float64      `json:"zoom_factor"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
